Update CoC and widen scope to community
netdata/netdata pull request #10186
Opened 2020-11-03 17:21 UTC by OdysLam

##### Summary

##### Component Name

##### Test Plan

##### Additional Information

2020-11-04 23:15 UTC, joelhans requested changes

2020-11-04 23:15 UTC, joelhans commented on CODE_OF_CONDUCT.md
> +contributors,maintainers and community members pledge to making participation in our project and
```suggestion
contributors, maintainers and community members pledge to making participation in our project and
```

2020-11-04 23:15 UTC, joelhans commented on CODE_OF_CONDUCT.md
> +reject comments, commits, code, wiki edits, issues, community posts and other contributions
```suggestion
reject comments, commits, code, documentation edits, issues, community posts, and other contributions
```

2020-11-09 15:58 UTC, aabatangle approved these changes

2020-11-09 16:07 UTC, joelhans approved these changes

2020-11-10 15:30 UTC, merged