Update README.md
netdata/netdata pull request #10214
Opened 2020-11-09 07:41 UTC by vincentkersten

Save a little time for the next gpu enabler

##### Summary

##### Component Name

##### Test Plan

##### Additional Information

2020-11-09 07:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netdata/netdata?pullRequest=10214) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netdata/netdata?pullRequest=10214) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netdata/netdata?pullRequest=10214) it.</sub>

2020-11-10 18:32 UTC, ilyam8 submitted a review, later dismissed

2020-11-10 22:16 UTC, joelhans requested changes
Thanks for the tweak, @vincentkersten!

Just a bit of formatting tweaks so that the Markdown renders nicely on the generated docs.

2020-11-10 22:16 UTC, joelhans commented on collectors/python.d.plugin/nvidia_smi/README.md
> +and remove the '#' before nvidia_smi so it reads: `nvidia_smi: yes`
```suggestion
-   You must enable this plugin, as its disabled by default due to minor performance issues:
    ```bash
    cd /etc/netdata   # Replace this path with your Netdata config directory, if different
    sudo ./edit-config python.d.conf
    ```
    Remove the '#' before nvidia_smi so it reads: `nvidia_smi: yes`.
```

2021-04-14 15:09 UTC, ilyam8 approved these changes

2021-04-14 15:11 UTC, vlvkobal approved these changes

2021-04-14 15:12 UTC, ilyam8 commented
@joelhans please review, can't merge until you approve it

2021-04-14 16:09 UTC, joelhans approved these changes

2021-04-14 16:41 UTC, merged