add paragraph to ask for feedback
netdata/netdata pull request #10363
Opened 2020-12-10 13:48 UTC by andrewm4894

##### Summary

add paragraph to ask for feedback

##### Component Name

docs

##### Test Plan

##### Additional Information

2020-12-10 15:31 UTC, joelhans commented on collectors/python.d.plugin/anomalies/README.md
> +**Note**: As this is a somewhat unique collector and involves often subjective concepts like anomalies and anomaly probabilities, we would love to hear any feedback on it from the community. Please d
Could we also (or instead) encourage users to post in the community forums? We could link to a category or even a specific thread. I don't really mind one way or another—just a thought.

```suggestion
**Note**: As this is a somewhat unique collector and involves often subjective concepts like anomalies and anomaly probabilities, we would love to hear any feedback on it from the community. Please drop us a note at [analytics-ml-team@netdata.cloud](mailto:analytics-ml-team@netdata.cloud) for any and all feedback, both positive and negative. This sort of feedback is priceless to help us make complex features more useful.
```

2020-12-11 10:58 UTC, andrewm4894 commented
@joelhans 100% agree on mentioning the community forums - added something in there. Also want to leave in the email option too in case some users might be happy to just shoot off and email but not want to share their experience in the public forums. Hopefully this gets us best of both worlds :)

2020-12-11 15:36 UTC, joelhans submitted a review, later dismissed

2020-12-14 09:13 UTC, OdysLam requested changes

2020-12-14 09:13 UTC, OdysLam commented on collectors/python.d.plugin/anomalies/README.md
> +**Note**: As this is a somewhat unique collector and involves often subjective concepts like anomalies and anomaly probabilities, we would love to hear any feedback on it from the community. Please l
Let's link them directly to the relevant forum category.

```suggestion
**Note**: As this is a somewhat unique collector and involves often subjective concepts like anomalies and anomaly probabilities, we would love to hear any feedback on it from the community. Please let us know on the [community forum](https://community.netdata.cloud/c/agent-development/9) or drop us a note at [analytics-ml-team@netdata.cloud](mailto:analytics-ml-team@netdata.cloud) for any and all feedback, both positive and negative. This sort of feedback is priceless to help us make complex features more useful.
```

2020-12-14 14:49 UTC, OdysLam approved these changes

2020-12-14 15:00 UTC, joelhans approved these changes

2020-12-14 19:31 UTC, merged