Spelling code
netdata/netdata pull request #10521
Opened 2021-01-19 06:45 UTC by jsoref

##### Summary

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

##### Component Name

##### Test Plan

The misspellings have been reported at https://github.com/jsoref/netdata/commit/33c5b20ed9511dac0a23ee916fa247cc2f388304#commitcomment-45444734

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/netdata/commit/e2737c090e4b1d7b1bce405b9f702bcf526852a3

##### Additional Information

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

This is split from #10428

2021-01-19 14:39 UTC, ilyam8 commented
@jsoref if you move all https://github.com/netdata/netdata/tree/master/collectors/python.d.plugin changes to a separate PR i can review it asap. Could you do it?

2021-01-19 14:53 UTC, jsoref commented
@ilyam8: I think that should do it. (sorry about the multiple pushes)

2021-01-19 14:56 UTC, ilyam8 commented
>  I think that should do it.

@jsoref i mean only the `collectors/python.d.plugin/**` files. This PR changes a lot of files from a lot of areas.

2021-01-20 14:14 UTC, underhood requested changes

2021-01-20 14:14 UTC, underhood commented on aclk/legacy/agent_cloud_link.h
> +#define ACLK_RECONNECT_DELAY 1 // reconnect delay -- with backoff strategy fow now
fow->for

2021-01-26 11:42 UTC, vlvkobal submitted a review, later dismissed

2021-04-05 20:12 UTC, ilyam8 commented
@jsoref thanks for your amazing work, we really appreciate it. It is a pity that it take so long to get it merged.

I think, to speed up the process, we can split the PR per area, so we have less reviewers in every PR.

This is the list of files with the changes:

```cmd
0 ~ $ curl   -s -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/netdata/netdata/pulls/10521/files | jq ".[] | .filename" | sort
"Dockerfile.test"
"aclk/legacy/aclk_common.c"
"aclk/legacy/aclk_lws_wss_client.c"
"aclk/legacy/aclk_lws_wss_client.h"
"aclk/legacy/aclk_query.c"
"aclk/legacy/aclk_rx_msgs.c"
"aclk/legacy/agent_cloud_link.c"
"aclk/legacy/agent_cloud_link.h"
"aclk/legacy/mqtt.c"
"aclk/legacy/tests/paho-inspection.py"
"backends/backends.c"
"build/m4/ax_gcc_func_attribute.m4"
"build_external/clean-install-arch-debug.Dockerfile"
"build_external/clean-install-arch-extras.Dockerfile"
"build_external/clean-install-arch.Dockerfile"
"build_external/scenarios/aclk-testing/paho-inspection.py"
"collectors/all.h"
"collectors/cgroups.plugin/sys_fs_cgroup.c"
"collectors/charts.d.plugin/charts.d.conf"
"collectors/charts.d.plugin/charts.d.plugin.in"
"collectors/checks.plugin/plugin_checks.c"
"collectors/cups.plugin/cups_plugin.c"
"collectors/diskspace.plugin/plugin_diskspace.c"
"collectors/ebpf.plugin/ebpf.c"
"collectors/ebpf.plugin/ebpf.h"
"collectors/ebpf.plugin/ebpf_apps.c"
"collectors/ebpf.plugin/ebpf_process.c"
"collectors/ebpf.plugin/ebpf_socket.c"
"collectors/freebsd.plugin/freebsd_devstat.c"
"collectors/freebsd.plugin/freebsd_getifaddrs.c"
```

I think we split it like:

- aclk

```cmd
"aclk/legacy/aclk_common.c"
"aclk/legacy/aclk_lws_wss_client.c"
"aclk/legacy/aclk_lws_wss_client.h"
"aclk/legacy/aclk_query.c"
"aclk/legacy/aclk_rx_msgs.c"
"aclk/legacy/agent_cloud_link.c"
"aclk/legacy/agent_cloud_link.h"
"aclk/legacy/mqtt.c"
"aclk/legacy/tests/paho-inspection.py"
```

- backends

```cmd
"backends/backends.c"
```

- build

```cmd
"Dockerfile.test"
"build/m4/ax_gcc_func_attribute.m4"
"build_external/clean-install-arch-debug.Dockerfile"
"build_external/clean-install-arch-extras.Dockerfile"
"build_external/clean-install-arch.Dockerfile"
"build_external/scenarios/aclk-testing/paho-inspection.py"
```

- collectors

```cmd
"collectors/all.h"
"collectors/cgroups.plugin/sys_fs_cgroup.c"
"collectors/charts.d.plugin/charts.d.conf"
"collectors/charts.d.plugin/charts.d.plugin.in"
"collectors/checks.plugin/plugin_checks.c"
"collectors/cups.plugin/cups_plugin.c"
"collectors/diskspace.plugin/plugin_diskspace.c"
"collectors/ebpf.plugin/ebpf.c"
"collectors/ebpf.plugin/ebpf.h"
"collectors/ebpf.plugin/ebpf_apps.c"
"collectors/ebpf.plugin/ebpf_process.c"
"collectors/ebpf.plugin/ebpf_socket.c"
"collectors/freebsd.plugin/freebsd_devstat.c"
"collectors/freebsd.plugin/freebsd_getifaddrs.c"
```

---

@vlvkobal @Ferroin what do you think guys, does it make sense? Would it be better then reviewing this PR?

2021-04-05 20:16 UTC, ilyam8 commented
Oh, wait, [i forgot](https://github.com/netdata/netdata/pull/10521#issuecomment-813622899) about _30 files per page_ limit. Let me redo the request.

2021-04-05 20:38 UTC, ilyam8 commented
Another idea 💡 is to move fix spelling in the comments (`# ...`, `// ...`) in a separate PR (easy to review and safe to merge).

2021-04-05 22:36 UTC, jsoref commented
I have 122 commits, to filter by comments, I can either flatten or filter I'd have to filter at a commit level (=122 times).

otoh, splitting at the directory/file type level is fairly cheap. So, as long as you're ok w/ directory/file level as a first split, that's definitely my preference.

2021-04-06 11:06 UTC, ilyam8 commented
Closing in favor of new PRs

2021-04-06 11:06 UTC, closed without merging