Improve ebpf plugin
netdata/netdata pull request #10756
Opened 2021-03-11 22:12 UTC by thiagoftsm

##### Summary
Fixes #10727 

Tomorrow I will have a meeting with product team and after this I will give more details about this PR.
##### Component Name

##### Test Plan

##### Additional Information

2021-03-16 10:29 UTC, vlvkobal commented
Please fix a Codacy issue.

2021-03-16 12:14 UTC, vlvkobal requested changes

2021-03-17 08:42 UTC, vlvkobal commented on libnetdata/ebpf/ebpf.c
> +void ebpf_load_config_update_module(ebpf_module_t *em, struct config *cfg, char *cfg_file)
What about this one? Don't you think that the existing name is a bit difficult to understand?

2021-03-17 13:37 UTC, thiagoftsm commented on libnetdata/ebpf/ebpf.c
> +void ebpf_load_config_update_module(ebpf_module_t *em, struct config *cfg, char *cfg_file)
I simplified the name now, please, take a look and mark this as resolved if it is more meaningful.

2021-03-17 16:52 UTC, vlvkobal approved these changes

2021-03-18 07:57 UTC, vlvkobal approved these changes

2021-03-18 09:39 UTC, underhood submitted a review, later dismissed

2021-03-18 12:14 UTC, underhood approved these changes

2021-03-18 12:18 UTC, vlvkobal approved these changes

2021-03-18 13:39 UTC, merged