Contributing revamp, take 2
netdata/netdata pull request #10956
Opened 2021-04-09 16:54 UTC by OdysLam

The final piece of a series of PRs across our repositories to align them in terms of contribution and community.

In short:

Remove the community health files (code of conduct, contributing, etc.) from every repo that they exist. They will be automatically sourced from the .github repository (GH docs).
Create new default community health files
Point Learn to source these files from .github
Revamp contributing guide and contributor journey
Align the README of main community-facing repos (netdata/netdata, netdata/dashboard, netdata/helmchart, netdata/go.d, netdata/community) as far as contributing and community guidelines are concerned.
Feedback is much appreciated :)

P.S contributors is removed because it is no longer updated.

2021-04-09 18:49 UTC, joelhans requested changes
Does sourcing from the new `.github` repo happen automatically, or is that some manual function you'll do once this PR is merged and the files deleted?

2021-04-09 18:49 UTC, joelhans commented on README.md
> +- [Menu](#menu)
I don't think we need this very self-referential item.

2021-04-09 18:49 UTC, joelhans commented on README.md
> +Netdata is striving to be an all inclusive open-source project and community. Please read our [Code of Conduct](https://learn.netdata.cloud/contribute/code-of-conduct).
Let's be a bit more confident here.

```suggestion
Netdata is an inclusive open-source project and community. Please read our [Code of Conduct](https://learn.netdata.cloud/contribute/code-of-conduct).
```

2021-04-09 18:49 UTC, joelhans commented on README.md
> +You can find most of the Netdata team in our [community forums](https://community.netdata.cloud). It's the best place to
```suggestion
Find most of the Netdata team in our [community forums](https://community.netdata.cloud). It's the best place to
```

2021-04-09 18:49 UTC, joelhans commented on README.md
> +Contributions are the lifeblood of OSS projects, such as Netdata Agent. While we are continuing to invest resources and improve the OSS Agent, we need every help we can get in our effort to democrati
```suggestion
Contributions are the lifeblood of open-source projects. While we continue to invest in and improve Netdata, we need help to democratize monitoring!
```

2021-04-09 18:49 UTC, joelhans commented on README.md
> +- View our [Security Policy](https://github.com/netdata/netdata/security/policy)
```suggestion
- Read our [Contributing Guide](https://learn.netdata.cloud/contribute/handbook), which contains all the information you need to contribute to Netdata, such as improving our documentation, engaging in the community, and developing new features. We've made it as frictionless as possible, but if you need help, just ping us on our community forums!
- We have a whole category dedicated to contributing and extending Netdata on our [community forums](https://community.netdata.cloud/c/agent-development/9)
- Found a bug? Open a [GitHub issue](https://github.com/netdata/netdata/issues/new?assignees=&labels=bug%2C+needs+triage&template=bug_report.md).
- View our [Security Policy](https://github.com/netdata/netdata/security/policy).
```

2021-04-09 19:05 UTC, ilyam8 commented
i wonder why netdatabot is a reviewer 🤖 😄

2021-04-14 17:31 UTC, joelhans commented
@OdysLam This LGTM, but you've got some issues with the changelog. I would recommend just aligning it to the latest version so that it doesn't keep bothering you about whatever you might have changed there.

2021-04-15 12:57 UTC, ilyam8 approved these changes

2021-04-15 16:15 UTC, joelhans approved these changes

2021-04-15 16:27 UTC, merged