Update k6.md
netdata/netdata pull request #11127
Opened 2021-05-10 16:19 UTC by odyslam

fix custom_edit url and add screenshot

##### Summary

##### Component Name

##### Test Plan

##### Additional Information

2021-05-10 19:02 UTC, ilyam8 requested changes

2021-05-10 19:02 UTC, ilyam8 commented on collectors/statsd.plugin/k6.md
> +custom_edit url: https://github.com/netdata/netdata/edit/master/collectors/statsd.plugin/k6.md
```suggestion
custom_edit_url: https://github.com/netdata/netdata/edit/master/collectors/statsd.plugin/k6.md
```

2021-05-10 19:15 UTC, ilyam8 commented on collectors/statsd.plugin/k6.md
> +![image](https://user-images.githubusercontent.com/13405632/117691411-8a7baf00-b1c4-11eb-9d87-8e9e7214871f.png)
```suggestion
## Metrics

![image](https://user-images.githubusercontent.com/13405632/117691411-8a7baf00-b1c4-11eb-9d87-8e9e7214871f.png)
```

2021-05-11 11:29 UTC, ilyam8 approved these changes

2021-05-11 18:36 UTC, joelhans approved these changes

2021-05-11 20:06 UTC, merged