Fix claim node examples in kickstart(-64) documentation
netdata/netdata pull request #11242
Opened 2021-06-11 17:57 UTC by cmd-ntrf

##### Summary

kickstart.sh and kickstart-64.sh flags cannot be set with equal sign because the option reading loop is expecting a space delimiter (i.e: shift statement). This PR removes the equal signs in the claim examples.

##### Component Name

Documentation

##### Test Plan

Trying the example with the equal signs lead to a failure to claim a node.

##### Additional Information

2021-06-11 17:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netdata/netdata?pullRequest=11242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netdata/netdata?pullRequest=11242) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netdata/netdata?pullRequest=11242) it.</sub>

2021-06-15 17:52 UTC, joelhans submitted a review, later dismissed
LGTM, but @Ferroin is the right person to verify that this is the intended/real behavior.

2021-12-20 14:36 UTC, ilyam8 requested changes

2021-12-20 14:36 UTC, ilyam8 commented on packaging/installer/methods/kickstart.md
> +bash <(curl -Ss https://my-netdata.io/kickstart.sh) --claim-token TOKEN --claim-rooms ROOM1,ROOM2
```suggestion
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --claim-token TOKEN --claim-rooms ROOM1,ROOM2 --claim-url https://app.netdata.cloud
```

I see that the claim URL is not set by default and it is required

https://github.com/netdata/netdata/blob/78c2af15478ea47e436ed58f0db827e5f37ba26d/packaging/installer/kickstart.sh#L519-L521

2021-12-20 14:36 UTC, ilyam8 commented on packaging/installer/methods/kickstart-64.md
> +bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --claim-token TOKEN --claim-rooms ROOM1,ROOM2
```suggestion
bash <(curl -Ss https://my-netdata.io/kickstart-static64.sh) --claim-token TOKEN --claim-rooms ROOM1,ROOM2 --claim-url https://app.netdata.cloud
```

I see that the claim URL is not set by default and it is required

https://github.com/netdata/netdata/blob/78c2af15478ea47e436ed58f0db827e5f37ba26d/packaging/installer/kickstart-static64.sh#L325-L327

2021-12-20 14:41 UTC, ilyam8 commented
Not setting the claim URL by default is a bug, should be set according to our docs ([1](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#connect-node-to-netdata-cloud-during-installation), [2](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64#connect-node-to-netdata-cloud-during-installation))

> --claim-url: Defaults to https://app.netdata.cloud.

cc @cpipilas @Ferroin worth fixing or not? considering that we are switching to kickstart-ng.

2021-12-20 14:54 UTC, Ferroin commented
> Not setting the claim URL by default is a bug, should be set according to our docs ([1](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart#connect-node-to-netdata-cloud-during-installation), [2](https://learn.netdata.cloud/docs/agent/packaging/installer/methods/kickstart-64#connect-node-to-netdata-cloud-during-installation))
> 
> > --claim-url: Defaults to https://app.netdata.cloud.
> 
> cc @cpipilas @Ferroin worth fixing or not? considering that we are switching to kickstart-ng.

Not sure how, but this appears to have been a case of something for the new kickstart script that hasn’t been officially released yet prematurely slipping into the documentation.

The existing script requires this parameter to be set, but the new one will not require it for the common case.

2021-12-20 14:57 UTC, ilyam8 approved these changes

2021-12-20 15:19 UTC, thiagoftsm approved these changes

2021-12-20 15:36 UTC, DShreve2 approved these changes

2021-12-21 07:45 UTC, merged