Fixed crash trying to access install-type before created
netdata/netdata pull request #11246
Opened 2021-06-15 08:34 UTC by tvarsis

Fixes #11228

2021-06-15 08:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netdata/netdata?pullRequest=11246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netdata/netdata?pullRequest=11246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netdata/netdata?pullRequest=11246) it.</sub>

2021-06-15 09:10 UTC, ilyam8 commented
@tvarsis thank you for fixing the issue 👍 Please, sign the CLA. That is required for a PR to get merged.

2021-06-15 11:26 UTC, Ferroin requested changes
While this does get rid of the error message, it creates other issues (namely, nightly static builds don’t properly record the build architecture that’s being installed).

The correct fix here is to wrap the whole function body in a conditional checking for the existence of the file referenced by `${install_type_file}`.

2021-06-17 11:53 UTC, Dexus commented
why removing it, and not use `[ -e "${install_type_file}" ] && . "${install_type_file}" ` to fix it?!

2021-06-17 11:54 UTC, Dexus requested changes

2021-06-17 11:54 UTC, Dexus commented on packaging/installer/kickstart-static64.sh
> -    . "${install_type_file}"
`[ -e "${install_type_file}" ] && . "${install_type_file}"` would be the best fix here!

2021-06-17 19:35 UTC, closed without merging