eBPF plugin remove parallel plugins
netdata/netdata pull request #11287
Opened 2021-06-29 02:08 UTC by thiagoftsm

##### Summary
After we have a short talk using Slack, I am bringing this PR to remove the possibility to have multiple eBPF plugins running in parallel.

I could not recreate the cited problem using kernel 5.12 many times, when the problem happened, it was thanks the fact I started another `netdata` instance before `eBPF.plugin` to be finished.

##### Component Name
ebpf.plugin
##### Test Plan

1 - Compile this PR
2 - Start Netdata, take a look at new file `/usr/libexec/netdata/plugins.d/ebpf.d/ebpf.pid`, it must have the current `PID` of `ebpf.plugin`
3 - Restart netdata and verify that you have only one `ebpf.plugin` running and the PID was updated inside the file.

##### Additional Information

2021-06-29 07:00 UTC, vlvkobal requested changes

2021-06-29 17:24 UTC, thiagoftsm commented on collectors/ebpf.plugin/ebpf.c
> +    procfile_close(ff);
You are right @vlvkobal , thank you!
The last commit fixed this. I had confusion with coverity yesterday, and I missed this. When I ran it I received email from `netdata/netdata` and I thought my PR did not have problems, but hours later I received another with this problem.

2021-06-29 18:44 UTC, vlvkobal approved these changes

2021-06-30 06:24 UTC, underhood approved these changes

2021-06-30 12:05 UTC, merged