Allow PushBullet notifications to be sent to PushBullet channels
netdata/netdata pull request #11850
Opened 2021-12-01 17:11 UTC by Grexeo

##### Summary
Allows notifications to be sent to PushBullet channels, in addition to or instead of PushBullet user email addresses.

A combination of user email addresses and/or channels can be specified, they are not exclusive. e.g:
`DEFAULT_RECIPIENT_PUSHBULLET="user1@example.com user2@example.com #channel1 #channel2"`

Channel tags must be prefixed with a hash (e.g. #channel), as explained in the updated README.md.

Backward compatible with only user email addresses being specified; does not remove or affect any existing functionality.

##### Component Name
PushBullet notifications

##### Test Plan
Tested with PushBullet channel names, email addresses and a combination of the two. All notifications received as expected.

##### Additional Information

2021-12-01 17:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netdata/netdata?pullRequest=11850) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netdata/netdata?pullRequest=11850) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netdata/netdata?pullRequest=11850) it.</sub>

2021-12-02 09:15 UTC, ilyam8 approved these changes

2021-12-02 11:53 UTC, ilyam8 commented on health/notifications/alarm-notify.sh.in
> +  local userapikey="${1}" source_device="${2}" recipients="${3}" url="${4}" title="${5}" message="${6}" httpcode sent=0 userOrChannelTag
> userOrChannelTag

Let's use snake case or (preferred imo) change it single word, e.g. "target".

2021-12-02 11:54 UTC, ilyam8 commented
Big thanks, @sourcecodes2. LGTM overall, I have only [one minor suggesstion](https://github.com/netdata/netdata/pull/11850#discussion_r761020881).

2021-12-03 13:41 UTC, DShreve2 approved these changes

2021-12-20 13:55 UTC, ilyam8 approved these changes

2021-12-20 16:04 UTC, kickoke requested changes
Updated the documentation to reflect our voice and tone.

2021-12-20 16:04 UTC, kickoke commented on health/notifications/pushbullet/README.md
> +4.  Add the recipient emails or channel tags (each channel tag must be prefixed with #, e.g. #channeltag) to DEFAULT_RECIPIENT_PUSHBULLET
```suggestion
4.  Add the recipient emails or channel tags (each channel tag must be prefixed with #, e.g. #channeltag) to `DEFAULT_RECIPIENT_PUSHBULLET`.
```

2021-12-20 16:04 UTC, kickoke commented on health/notifications/pushbullet/README.md
> +    !!PLEASE NOTE THAT IF AN EMAIL RECIPIENT DOES NOT HAVE A PUSHBULLET ACCOUNT, PUSHBULLET SERVICE WILL SEND AN EMAIL!!
```suggestion
    > 🚨 The pushbullet notification service will send emails to the email recipient, regardless of if they have a pushbullet account.
```

2021-12-20 16:04 UTC, kickoke commented on health/notifications/pushbullet/README.md
>  Set them in `/etc/netdata/health_alarm_notify.conf` (to edit it on your system run `/etc/netdata/edit-config health_alarm_notify.conf`), like this:
```suggestion
To add notification channels, run `/etc/netdata/edit-config health_alarm_notify.conf` 

You can change the configuration like this:
```

2021-12-21 15:45 UTC, thiagoftsm commented
Hey @sourcecodes2 , please, can you address @kickoke suggestions for we have conditions to merge your PR. Thanks!

2021-12-21 15:49 UTC, ilyam8 approved these changes

2021-12-21 15:57 UTC, thiagoftsm approved these changes

2021-12-21 15:58 UTC, ilyam8 commented on health/notifications/alarm-notify.sh.in
> +  local userapikey="${1}" source_device="${2}" recipients="${3}" url="${4}" title="${5}" message="${6}" httpcode sent=0 userOrChannelTag
A minor suggestion, not a blocker for merging.

2021-12-22 13:37 UTC, kickoke approved these changes

2022-01-11 10:43 UTC, merged