fixed username for not-local users
netdata/netdata pull request #11854
Opened 2021-12-02 10:08 UTC by scatenag

fix https://github.com/netdata/netdata/issues/10264

2021-12-02 11:24 UTC, ilyam8 approved these changes

2021-12-02 14:16 UTC, vlvkobal submitted a review, later dismissed

2021-12-02 16:17 UTC, Ferroin requested changes
@scatenag Either pull bot needs to be disabled for your fork of this repo, or you need to recreate the PR from a topic branch. Otherwise, pull bot will just wipe any changes

2021-12-02 23:41 UTC, merged

2021-12-03 00:30 UTC, ilyam8 commented
Fixed 😄

2021-12-03 07:56 UTC, scatenag commented
> @scatenag Either pull bot needs to be disabled for your fork of this repo, or you need to recreate the PR from a topic branch. Otherwise, pull bot will just wipe any changes

I recreated the PR https://github.com/netdata/netdata/pull/11858 disabling pull-bot.
@Ferroin : thanks for pointing me that and sorry for the confusion :man_facepalming:.