Track anomaly rates with DBEngine.
netdata/netdata pull request #12083
Opened 2022-02-03 15:52 UTC by vkalintiris

##### Summary

This commit adds support for tracking anomaly rates with DBEngine. We
do so by creating a single chart with id "anomaly_detection.anomaly_rates" for
each trainable/predictable host, which is responsible for tracking the anomaly
rate of each dimension that we train/predict for that host.

The rrdset->state->is_ar_chart boolean flag is set to true only for anomaly
rates charts. We use this flag to:

    - Disable exposing the anomaly rates charts through the functionality
      in backends/, exporting/ and streaming/.
    - Skip generation of configuration options for the name, algorithm,
      multiplier, divisor of each dimension in an anomaly rates chart.
    - Skip the creation of health variables for anomaly rates dimensions.
    - Skip the chart/dim queue of ACLK.
    - Post-process the RRDR result of an anomaly rates chart, so that we can
      return a sorted, trimmed number of anomalous dimensions.

In a child/parent configuration where both the child and the parent run
ML for the child, we want to be able to stream the rest of the ML-related
charts to the parent. To be able to do this without any chart name collisions,
the charts are now created on localhost and their IDs and titles have the node's
machine_guid and hostname as a suffix, respectively.

##### Test Plan

- Local & CI builds.
- Staging once merged.

2022-02-03 16:13 UTC, vkalintiris commented on ml/Config.cc
> +    bool EnableAnomalyDetection = config_get_boolean(ConfigSectionML, "enabled", true);
Most of the changes in this file are meant to make testing easy and they will be reverted prior to merging the PR. ML is enabled and detection/prediction runs every minute just for the `system.cpu` chart. The anomaly rates are updated every 5 seconds.

2022-02-04 09:30 UTC, MrZammler commented
My concern as we discussed briefly. If the anomaly rate chart is not streamed to a parent (that is claimed) and the child is not claimed, I don't know if it's possible for the cloud to query for this data the parent on behalf of the child.

The routing as referred by the cloud backend, is that when they want to get data for a child through a parent, they issue a query like '/node/XXXXXXXX/api/v1/something' on the parent, but those data are stored on the parent and it can reply for those. @stelfrag / @underhood if I'm wrong on this maybe?

It's kinda like alerts, i.e. they can get alerts for a child, but only if the parent has calculated them (not the ones calculated by the child).

2022-02-08 14:46 UTC, MrZammler commented
Hi Vasili!

We seem at first glance, to be sending the chart to the cloud (this is via the new arch - just a single claimed node):

![image](https://user-images.githubusercontent.com/1905463/153010574-3dce2892-8700-4d46-92dd-fe1493d0095a.png)

2022-02-08 15:51 UTC, vkalintiris commented
> We seem at first glance, to be sending the chart to the cloud (this is via the new arch - just a single claimed node):

We have two charts:
   -  "anomaly_detection.anomaly_rate": contains 1 dim with the anomaly rate of the host, ie. `num_anomalous_dims / num_total_dims`.
   - "anomaly_detection.anomaly_rate**s**": contains many dimensions, ie. one for each trainable dimension.

2022-02-14 15:26 UTC, underhood commented
had it seqfault:
```
#0  0x000000000044f59c in rrdset2anything_api_v1 (st=st@entry=0x9c1b2c0, wb=0x6ae7df0, dimensions=dimensions@entry=0x0, format=format@entry=0, points=points@entry=432, after=after@entry=-900, before=0, group_method=1, group_time=0, 
    options=547, latest_timestamp=0x7f59605c17f0, context_param_list=0x6c6d550, chart_label_key=0x0, max_anomaly_rates=0) at web/api/formatters/rrd2json.c:232
#1  0x0000000000456ab8 in web_client_api_request_v1_data (host=0x2efe130, w=0xb9e7e40, url=<optimized out>) at web/api/web_api_v1.c:614
#2  0x0000000000457f01 in web_client_api_request_v1 (host=host@entry=0x2efe130, w=w@entry=0xb9e7e40, url=url@entry=0xb98c0f2 "data") at web/api/web_api_v1.c:1320
```

2022-02-14 15:56 UTC, underhood requested changes
above comments

2022-02-14 16:03 UTC, vkalintiris commented
> had it seqfault:

Can you post the request so that I can take a look?

2022-02-14 16:22 UTC, underhood commented
Was a cloud request when i scrolled to the anomaly chart which failed to load. Dont have anymore the exact request but i can try reproduce.

2022-02-14 16:28 UTC, vkalintiris commented
> Was a cloud request when i scrolled to the anomaly chart which failed to load. Dont have anymore the exact request but i can try reproduce.

That makes me even more curious about what happened, can you reproduce this? On cloud, we only show the host's "anomaly rate" chart (ie. not the "anomaly rates" as described here https://github.com/netdata/netdata/pull/12083#issuecomment-1032759658).

2022-02-14 16:34 UTC, underhood commented
seems to crash on this:
```
0x63f3a60 "GET /node/e41348ff-f917-4a58-9ee6-189891f9ec37/api/v1/data?v2=&chart=anomaly_detection.dimensions&format=json&options=jsonwrap%7Cnonzero%7Cflip%7Cms&_=1644856250370&points=432&group=average&gtime=0&after=-900 HTTP/1.1\r\nHost: cloud-agent-data-ctrl-service.app\r\nAccept-Encoding: gzip\r\nMqtt-Broker-Addr: vernemq-1.vernemq-headless.infra:1883\r\nNetdata-Request-Id: 8YCwXP0cSO-2772813\r\nUser-Agent: Go-http-client/2.0\r\n\r\n"
```
here
![Screenshot from 2022-02-14 17-33-19](https://user-images.githubusercontent.com/6674623/153905698-fdb8593d-af0f-4c4f-ab3c-0480eb4e77db.png)

Steps to reproduce:
1.did clean build from this PR/branch
1.netdata -D
1.wait agent is connected to staging
1. go to single node view of this node - all charts load
2. click anomaly group shortcut in menu on the right side

2022-02-14 17:11 UTC, andrewm4894 commented
my comment above would explain the crash @underhood mentions since `chart=anomaly_detection.dimensions` does not exist but `chart=anomaly_detection.dimensions_<some random number>` would exist. 

e.g. on one of my nodes it's `anomaly_detection.dimensions_ba9c3782-8da5-11ec-9aee-42010a8e003c`

![image](https://user-images.githubusercontent.com/2178292/153912444-346cfe17-0cc8-4814-8313-f472576fb673.png)

2022-02-15 09:48 UTC, andrewm4894 commented
@vkalintiris would we be able to remove the chart renaming to unique from this PR and handle it separately. My understanding is that doing so will not break anything and then we can tackle the parent/child and renaming stuff separate maybe. Will think about it but i can see lots of potential unintended consequences of adding the suffix on the agent side and it just does not feel like an elegant solution to me. 

Ideally maybe cloud should be able to figure it all out would be my hope since it should know what it needs about each node instance. If it needs to know more to handle this specific case then we should add what it needs to the ml-info endpoint instead of sort of breaking the naming conventions of charts.

2022-02-15 09:51 UTC, andrewm4894 commented
> If we don't have a unique name for the newly created charts on the parent, then there will be a collision of chart names. That is, a parent will receive the child's anomaly_detection.dimension chart through streaming, and then try to add its own data to the same anomaly_detection.dimension chart if it runs ML for the child.

Could the parent not just handle this and just overwrite the `anomaly_detection.` charts for now. Such that if you configure ml on a parent then it will be those `anomaly_detection.` charts based on the parent ml config that you see.

2022-02-17 09:51 UTC, andrewm4894 commented
this is looking good to me know and seems to be working as expected

2022-02-22 12:43 UTC, andrewm4894 submitted a review, later dismissed

2022-02-22 14:50 UTC, thiagoftsm commented
Hello @vkalintiris ,

Please, take a look at [this LGTM](https://github.com/netdata/netdata/pull/12083#issuecomment-1047636718) report.

2022-02-22 15:17 UTC, MrZammler commented
For the ACLK part, I think it's ok. I got the chart in `http://localhost:19999/api/v1/data?chart=anomaly_detection.anomaly_rates`, but there's no sign of it in messages to the cloud.

2022-02-23 09:55 UTC, vkalintiris commented
I forgot to add an empty commit after rebasing the branch. These are the only new changes I added based on review feedback:
![changes](https://user-images.githubusercontent.com/25480816/155296518-3bb3a303-6d09-440c-be3f-8db962150c8b.png)

2022-02-23 17:39 UTC, thiagoftsm commented
> @andrewm4894 I believe the reviewers are pretty much okay to accept this after addressing the latest comments. @thiagoftsm @MrZammler @underhood: what do you think?

I agree 100%.
In time, I already tested this PR and it is working as expected.

2022-02-23 19:46 UTC, andrewm4894 approved these changes
Lgtm

2022-02-23 19:55 UTC, thiagoftsm approved these changes

2022-02-24 08:32 UTC, MrZammler approved these changes

2022-02-24 08:54 UTC, underhood approved these changes

2022-02-24 08:57 UTC, merged