Add retries in preparation of test environments for build CI.
netdata/netdata pull request #12198
Opened 2022-02-21 12:48 UTC by Ferroin

##### Summary

This particular part of our CI fails relatively frequently due to external infrastructure problems. By retrying on the first few failures
in a run, we should mitigate most of these issues at the cost of making the worst case runtime about 10 minutes longer.

##### Test Plan

There should be no visible changes in the running CI on this PR relative to any of the others.

2022-03-03 12:56 UTC, Ferroin commented
Rebased to resolve merge conflict.

2022-03-11 10:26 UTC, maneamarius requested changes
Would using the action `nick-invision/retry@v2` be better, instead of copy-pasting same steps 3 times?
I've done that here:
https://github.com/netdata/saltstack/blob/develop/.github/workflows/vagrant.yml#L108-L114

2022-03-11 12:03 UTC, Ferroin commented
@maneamarius Excellent suggestion, I completely forgot about that possibility.

2022-03-11 12:34 UTC, Ferroin commented
@maneamarius Ah, no, I remember now why I did not use that action for this. It only supports `run` style steps, not retrying other actions, and this is a case where the probelmatic step is another action and not just some shell script that needs retried.

2022-03-15 07:44 UTC, maneamarius commented
I still don't like copy-pasting the retry steps 3 times.
I'd rather just use the plain docker commands in a script (instead of using the docker build/push action), and use `nick-invision/retry@v2` action with that script..
But if you're happy with the current implementation, I don't have major objections, we can merge as-is.

2022-03-16 11:33 UTC, merged