Add proper handling for legacy kickstart install detection.
netdata/netdata pull request #12273
Opened 2022-02-28 19:02 UTC by Ferroin

##### Summary

By properly looking for and parsing the `.environment` file if we do not see a `.install-type` file.

This particular case was not handled in the existing code as it was assumed that a majority of users would have gotten updated since their original install to a version that did properly include the `.install-type` file.

##### Test Plan

Primary test cases can be replicated with the current kickstart script as follows:

* To simulate a `legacy-build` install type (local source build done with the old kickstart script, or possibly by manually running the `netdata-installer.sh` script), install with the `--build-only` option using the new kickstart script, and then remove `/etc/netdata/.install-type`.
* To simulate a `legacy-static` install type (static install done by the old kickstart-static64.sh script before the `.install-type` file became a thing), install with the `--static-only` option using the new kickstart script and then remove `/opt/netdata/etc/netdata/.install-type`.

2022-02-28 19:20 UTC, ilyam8 commented on packaging/installer/kickstart.sh
> +          INSTALL_TYPE="legacy-stati"
```suggestion
          INSTALL_TYPE="legacy-static"
```

2022-02-28 19:22 UTC, Ferroin commented on packaging/installer/kickstart.sh
> +          INSTALL_TYPE="legacy-stati"
Nice catch.

2022-03-02 06:33 UTC, cronlabspl requested changes
Plain NO for this. Had this code be written 10 years ago, than it'd suffice.

2022-03-02 12:20 UTC, maneamarius approved these changes

2022-03-03 12:51 UTC, merged