Configurable storage engine for Netdata agents: step 1
netdata/netdata pull request #12776
Opened 2022-04-28 20:15 UTC by aberaud

Following the idea discussed here:
https://github.com/netdata/netdata/discussions/12216

This PR introduces some minor cleanups that could be merged independently, and allowing to introduce more changes in subsequent pull requests.

##### Summary

These commits do the following (in commit order):
* Move `rrddim_collect_ops` and `rrddim_query_ops` out of the `rrddim_volatile` structure, allowing them to be used outside of the context of this structure. Later, we plan to use these structures to allow storage engines to expose their collection and query APIs.
* Make `rrddim_collect_handle` and `rrddim_query_handle` opaque structures instead of a union, allowing for arbitrary handle types, later provided by arbitrary memory modes/storage engines.

##### Test Plan

These changes don't add any new memory modes/storage engines for now, and only refactor existing features, so they are expected to be covered by existing unit tests.

2022-05-02 11:48 UTC, vkalintiris submitted a review, later dismissed

2022-05-02 14:14 UTC, thiagoftsm commented
Hello @aberaud ,

I tested your PR now and I observed that it is working as expected, but before I approve your PR, I would like to require you to fix these warnings:

```sh
database/rrddim.c: In function 'rrddim_query_init':
database/rrddim.c:127:20: warning: assignment to 'STORAGE_QUERY_HANDLE *' {aka 'struct storage_query_handle *'} from incompatible pointer type 'struct mem_query_handle *' [-Wincompatible-pointer-types]
  127 |     handle->handle = mem_handle;
      |                    ^
database/rrddim.c: In function 'rrddim_query_next_metric':
database/rrddim.c:132:43: warning: initialization of 'struct mem_query_handle *' from incompatible pointer type 'STORAGE_QUERY_HANDLE *' {aka 'struct storage_query_handle *'} [-Wincompatible-pointer-types]
  132 |     struct mem_query_handle* mem_handle = handle->handle;
      |                                           ^~~~~~
database/rrddim.c: In function 'rrddim_query_is_finished':
database/rrddim.c:148:43: warning: initialization of 'struct mem_query_handle *' from incompatible pointer type 'STORAGE_QUERY_HANDLE *' {aka 'struct storage_query_handle *'} [-Wincompatible-pointer-types]
  148 |     struct mem_query_handle* mem_handle = handle->handle;
      |                                           ^~~~~~
 OK  ''
```

Best regards!

2022-05-02 14:51 UTC, odynik requested changes
Simple warning fixes and then I will approve the PR.
> EDIT:
@thiagoftsm came first :) . Same as [comment](https://github.com/netdata/netdata/pull/12776#issuecomment-1114937329).

2022-05-02 19:51 UTC, aberaud commented on database/rrddim.c
> +    handle->handle = mem_handle;
Done

2022-05-02 19:51 UTC, aberaud commented on database/rrddim.c
> +    struct mem_query_handle* mem_handle = handle->handle;
Done

2022-05-02 19:51 UTC, aberaud commented on database/rrddim.c
> +    struct mem_query_handle* mem_handle = handle->handle;
Done

2022-05-02 21:46 UTC, vkalintiris approved these changes

2022-05-02 22:03 UTC, thiagoftsm approved these changes
I retest on Linux and with last commits `dbengine` and `ram` are running as expected. LGTM!

2022-05-03 06:23 UTC, odynik approved these changes

2022-05-03 08:34 UTC, merged