Send collectors to the cloud
netdata/netdata pull request #13013
Opened 2022-05-26 10:48 UTC by MrZammler

##### Summary

This PR gathers a list of collectors (per host) and sends them to the cloud via the `UpdateNodeInfo` message.

The produced part of the `UpdateNodeInfo` message looks like:

```
       "collectors" => [
            [ 0] "freebsd.plugin:vm.stats.sys.v_soft",
            [ 1] "freebsd.plugin:vm.vmtotal",
            [ 2] "freebsd.plugin:net.inet.ip.stats",
            [ 3] "freebsd.plugin:net.isr",
            [ 4] "freebsd.plugin:vm.stats.vm.v_swappgs",
            [ 5] "freebsd.plugin:net.inet.icmp.stats",
            [ 6] "idlejitter.plugin:",
            [ 7] "freebsd.plugin:kern.ipc.msq",
            [ 8] "freebsd.plugin:net.inet6.icmp6.stats",
            [ 9] "freebsd.plugin:kern.ipc.sem",
            [10] "statsd.plugin:stats",
            [11] "freebsd.plugin:kern.ipc.shm",
            [12] "freebsd.plugin:system.ram",
            [13] "freebsd.plugin:getifaddrs",
            [14] "freebsd.plugin:kern.cp_times",
            [15] "freebsd.plugin:uptime",
            [16] "freebsd.plugin:net.inet6.ip6.stats",
            [17] "freebsd.plugin:vm.stats.sys.v_intr",
            [18] "freebsd.plugin:vm.stats.sys.v_swtch",
            [19] "freebsd.plugin:net.inet.tcp.states",
            [20] "freebsd.plugin:hw.intrcnt",
            [21] "freebsd.plugin:vm.stats.vm.v_pgfaults",
            [22] "freebsd.plugin:getmntinfo",
            [23] "freebsd.plugin:net.inet.tcp.stats",
            [24] "freebsd.plugin:dev.cpu.0.freq",
            [25] "freebsd.plugin:devstat",
            [26] "freebsd.plugin:kern.cp_time",
            [27] "freebsd.plugin:net.inet.udp.stats",
            [28] "freebsd.plugin:vm.swap_info"
        ]
```
The `:` character is used as a separator between modules and plugins and the above format has been discussed with BE.

##### Test Plan

No easy way to check that the message is updated with the collectors, unless the `aclk-log` (ACLK_LOG_CONVERSATION_DIR) feature is used that dumps the messages to disk.

We will get an okay from Cloud BE before merging.

##### Additional Information

We might or might not need to adjust when the `UpdateNodeInfo` goes out. If it goes too early then the list of collectors might be less than the reality. There is however logic to re-send these messages at later times so it might not be an issue. We should look if there is need to re-send e.g. when a chart (and it's collector) dissapears.

<details> <summary>For users: How does this change affect me?</summary>
  
It will provide info on the services supported by this agent on the cloud.
</details>

2022-05-26 11:10 UTC, underhood commented
`The : character is used as a separator between modules and plugins and the above format has been discussed with BE.`
not a fan of this TBH.

Why not define:
```
message collectorinfo {
string module,
string plugin
}
```

and embed it?

2022-05-26 11:15 UTC, underhood requested changes
comments above

2022-05-26 11:16 UTC, underhood commented
also superquick peek at the code here:
```
char **collectors_from_charts(RRDHOST *host, size_t *count) {
    DICTIONARY *dict = dictionary_create(DICTIONARY_FLAG_SINGLE_THREADED);
    RRDSET *st;
    char name[500];

    time_t now = now_realtime_sec();
    rrdhost_rdlock(host);
    rrdset_foreach_read(st, host) {
        if (rrdset_is_available_for_viewers(st)) {
            struct collector col = {
                    .plugin = st->plugin_name ? st->plugin_name : "",
                    .module = st->module_name ? st->module_name : ""
            };
            snprintfz(name, 499, "%s:%s", col.plugin, col.module);
            dictionary_set(dict, name, &col, sizeof(struct collector));
            st->last_accessed_time = now;
        }
    }
    rrdhost_unlock(host);

    struct array_printer ap;
    ap.c = 0;
    ap.collectors = NULL;

    dictionary_get_all(dict, store_collectors, &ap);
    dictionary_destroy(dict);

    *count = ap.c;
    return ap.collectors;
}
```

Isn't cloud able to do the same?

2022-05-26 12:29 UTC, MrZammler commented
> > The : character is used as a separator between modules and plugins and the above format has been discussed with BE
> 
> not a fan of this TBH.
> 
> Why not define:
> 
> ```
> message collectorinfo {
> string module,
> string plugin
> }
> ```
> 
> and embed it? `repeated colectorinfo collectors = 23;`

Hi Timo!

We could I guess, yes. Depends though on BE and what they have already implemented. Services was a string array so I picked from there. We can discuss with them, sure.

2022-05-26 12:37 UTC, MrZammler commented
> Isn't cloud able to do the same? (build the list from the chart list? assuming we already have reliable chart list sync)

It could yes, but I think of it as a bit of offloading stuff to the edge than having the cloud do it for every node. But again, can be discussed.

2022-05-26 12:53 UTC, underhood commented
> > > We might or might not need to adjust when the UpdateNodeInfo goes out. If it goes too early then the list of collectors might be less than the reality. There is however logic to re-send these messages at later times so it might not be an issue. We should look if there is need to re-send e.g. when a chart (and it's collector) dissapears.
> > 
> > 
> > I worry about this a bit. In old ACLK JSON protocol we used to send huge message with collectors, charts lists etc. New arch. was supposed to remove such issues and only send what changed.
> > Then we had to do things like infamous `popcorning` etc. I worry UpdateNodeInfo will become same thing. Should we think about separating collector sync to separate message?
> > In general we try to send only stuff we have to send, so lets be careful about creating big compound messages serving multiple purposes.
> 
> Agreed, but again depends on the backend. My feeling is that they overwrite what's already there when they receive a new UpdateNodeInfo. I understand what you're saying, but I don't know if the list of collectors falls in the same category as charts and alerts. It should not be that big, or that common to exchange to support the effort to keep them up-to-date with deltas. But we can discuss.

yes deltas would be super overkill here

2022-06-08 10:29 UTC, vkuznecovas commented
Sorry was on vacation for most of this discussion.

I'm reluctant to recalculate these on the cloud side. The reason is rather simple - performance. The charts database is already under load and if we're looking into the far future it makes sense to do the least amount possible on the cloud itself and leverage the agents. 

Therefore, I would suggest the following. 

1) Implement a new message that the agent would send to the cloud `UpdateNodeCollectors`. The message would look like this:

```proto
message collectorinfo {
  string module = 1;
  string plugin = 2;
}

message UpdateNodeCollectors {
  string claim_id = 1;
  string node_id = 2;
  repeated colectorinfo collectors = 23;

  int32 vmq_instance_id = 4;
}
```

2) The agent determines the appropriate times to send this message.
3) The cloud starts accepting this message.
4) The cloud maps these collectors to services when the message arrives and saves the information for further use.

Thoughts, opinions? @underhood @MrZammler 

cc: @papazach

2022-06-08 14:23 UTC, underhood commented
@vkuznecovas I like the idea. Basically what I was suggesting.

2022-06-09 14:31 UTC, MrZammler commented
No problem by me having a new message! I'll have a go, unless @papazach or @stelfrag have a different opinion.

2022-06-10 14:36 UTC, papazach commented
> No problem by me having a new message! I'll have a go, unless @papazach or @stelfrag have a different opinion.

Hey @MrZammler @underhood @vkuznecovas sorry for the delayed response here.
I totally agree with the payload proposed by Viktoras as well, I think it fits our case very well 👍🏼 

So just to verify the behavior also:
Each time that the `UpdateNodeCollectors` is received it will state the current set of the modules/plugins used by the Agent. 
So each time a module/plugin is added/removed we'll get a new `UpdateNodeCollectors` with the current state.

Just to verify that this will not work in a diffing way or something like that.

2022-06-10 14:39 UTC, MrZammler commented
@papazach Yes, this is the way.

2022-07-07 18:53 UTC, MrZammler commented
PR https://github.com/netdata/netdata/pull/13330 has been merged.

2022-07-07 18:53 UTC, closed without merging