Finish renaming the `--install` option to `--install-prefix`.
netdata/netdata pull request #13881
Opened 2022-10-25 11:53 UTC by Ferroin

##### Summary

SSIA

##### Test Plan

Attempting to use `--install` with the kickstart script or netdata-installer.sh should not result in the agent being installed to the specified prefix.

##### Additional Information

Fixes: #12659 

Should not be merged before #12943 (otherwise the error messages for the user will be more confusing).

2022-12-02 22:32 UTC, Dim-P requested changes
@Ferroin Some more places that there is a reference to or a use of `--install`, I am sure some are obsolete references, but IMO they should all be updated until removed completely:

- [run_install_with_dist_file.sh](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/.github/scripts/run_install_with_dist_file.sh#L36)
- [checks.yml](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/.github/workflows/checks.yml#L54)
- [codeql.yml](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/.github/workflows/codeql.yml#L90)
- [claim/README.md](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/claim/README.md?plain=1#L291)
- [claim/README.md #2](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/claim/README.md?plain=1#L386)
- [claim/README.md #3](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/claim/README.md?plain=1#L541)
- [UNINSTALL.md](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/UNINSTALL.md?plain=1#L54)
- [UPDATE.md](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/UPDATE.md?plain=1#L48)
- [UPDATE.md #2](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/UPDATE.md?plain=1#L64)
- `kickstart-static64.sh` similarly to `kickstart.sh`
- `kickstart-ng.sh` similarly to `kickstart.sh`
- [freebsd.md](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/methods/freebsd.md?plain=1#L48)
- [freebsd.md #2](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/methods/freebsd.md?plain=1#L78)
- [macos.md](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/methods/macos.md?plain=1#L51)
- [macos.md #2](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/methods/macos.md?plain=1#L96)
- [manual.md](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/packaging/installer/methods/manual.md?plain=1#L192)
- [lifecycle.bats](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/tests/lifecycle.bats#L37)
- [run-unit-tests.sh](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/tests/run-unit-tests.sh#L24)
- [updater_checks.bats](https://github.com/Ferroin/netdata/blob/7d5d39c77b5e589a97e3667926f05d59b1dd6799/tests/updater_checks.bats#L37)

2022-12-03 16:34 UTC, thiagoftsm commented
The PR is working as expected, but I am waiting for additional commit to address [this](https://github.com/netdata/netdata/pull/13881#pullrequestreview-1203196650)

2022-12-07 12:39 UTC, Ferroin commented
Rebased to pick up CI changes, and fixed remaining references to the `--install` option.

2022-12-07 12:53 UTC, thiagoftsm commented on .travis.yml
> +      script: fakeroot ./netdata-installer.sh --install-prefix $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto
@Ferroin , please, take a look in the next `yamllint` report.

2022-12-08 14:24 UTC, Dim-P reviewed
Whoops, only just realised `kickstart-static64.sh` and `kickstart.ng` are symbolic links :P . Looks good other than the `yamllint` failure pointed out by @thiagoftsm , I will approve it once that gets fixed.

2022-12-08 14:28 UTC, ilyam8 commented
@Dim-P @thiagoftsm line characters limit shouldn't be checked for ci files (we just never set up different yamllint rules for ci/everything else), you can ignore that warning.

2022-12-08 20:07 UTC, thiagoftsm approved these changes
Considering last comment and another successful test, LGTM!

2022-12-08 21:21 UTC, Dim-P approved these changes

2023-01-04 12:34 UTC, merged