Switch to self-hosted infrastructure for RPM package distribution.
netdata/netdata pull request #14100
Opened 2022-12-07 16:00 UTC by Ferroin

##### Summary

This updates our repository configuration packages to point to our new self-hosted repository infrastructure for our RPM packages. A secondary PR migrating DEB package infrastructure will be created later.

##### Test Plan

The repository configuration can be tested by copying the `netdata*.repo.*` file for the distribution to be tested on (`centos` for Alma/CentOS/RHEL/Rocky, `ol` for Oracle Linux, `fedora` for Fedora, `suse` for openSUSE) to the test system and putting it in the appropriate directory (`/etc/yum.repos.d` on most distros, or `/etc/zypp/repos.d` on openSUSE) with the correct name (just remove the `.<distro>` extension).

After setting up the repository configuration, refreshing metadata or attempting to install a package should result in a prompt about accepting a new GPG key for netdatabot. Errors are expected for the Netdata Repository Config repository at the moment (we have no packages in that repo yet on the new infrastructure).

2022-12-07 18:35 UTC, thiagoftsm commented
@Ferroin we are only having nightly for [edge](https://repo.netdata.cloud/repos/edge/el/), should we have at least the latest stable there?

2022-12-07 18:40 UTC, thiagoftsm commented
@Ferroin , please, forget previous message, I saw now that we have another link for stable.

2022-12-07 18:50 UTC, thiagoftsm commented
Now without mistakes. I have observed that we are not having the same versions for plugins and Netdata on [this](https://repo.netdata.cloud/repos/edge/opensuse/15.4/x86_64/) link. Why are we missing a package `1.36.0.406` for `netdata`?

2022-12-08 12:52 UTC, Ferroin commented
> Now without mistakes. I have observed that we are not having the same versions for plugins and Netdata on [this](https://repo.netdata.cloud/repos/edge/opensuse/15.4/x86_64/) link. Why are we missing a package `1.36.0.406` for `netdata`?

There was a bug in the code that was copying the packages into the repository directory. It’s been fixed now, though it may take a while for the changes to be live (I still don’t have the cache invalidation set up properly yet).

2022-12-08 21:24 UTC, thiagoftsm commented
> There was a bug in the code that was copying the packages into the repository directory. It’s been fixed now, though it may take a while for the changes to be live (I still don’t have the cache invalidation set up properly yet).

Thank you to explain, I will take a look again tomorrow.

2022-12-09 18:23 UTC, thiagoftsm commented
On  `CentOS 7.9` I observed that I cannot start neither `apps` nor `ebpf.plugin` because they are taking a look in wrong directories:

```sh
[root@192 ~]# /usr/libexec/netdata/plugins.d/ebpf.plugin 
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file process.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file network.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file cachestat.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file sync.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file dcstat.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file swap.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file vfs.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file filesystem.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file disk.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file mount.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file fd.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file hardirq.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file softirq.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file oomkill.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file shm.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file mdflush.conf (errno 2, No such file or directory)
2022-12-09 18:20:52:  INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/etc/netdata/conf.d/apps_groups.conf'
2022-12-09 18:20:52:  ERROR : MAIN : Cannot read process groups '/etc/netdata/conf.d/apps_groups.conf'. There are no internal defaults. Failing. (errno 2, No such file or directory)
[root@192 ~]# /usr/libexec/netdata/plugins.d/apps.plugin 
2022-12-09 18:21:10: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf' (errno 2, No such file or directory)
2022-12-09 18:21:10: apps.plugin INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/etc/netdata/conf.d/apps_groups.conf'
2022-12-09 18:21:10: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/conf.d/apps_groups.conf' (errno 2, No such file or directory)
2022-12-09 18:21:10: apps.plugin ERROR : MAIN : Cannot read process groups '/etc/netdata/conf.d/apps_groups.conf'. There are no internal defaults. Failing.
```

Stock files should be at `/usr` instead the cited directory.

2022-12-12 12:12 UTC, Ferroin commented
> On `CentOS 7.9` I observed that I cannot start neither `apps` nor `ebpf.plugin` because they are taking a look in wrong directories:
> 
> ```shell
> [root@192 ~]# /usr/libexec/netdata/plugins.d/ebpf.plugin 
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file process.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file network.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file cachestat.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file sync.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file dcstat.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file swap.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file vfs.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file filesystem.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file disk.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file mount.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file fd.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file hardirq.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file softirq.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file oomkill.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file shm.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot load the ebpf configuration file mdflush.conf (errno 2, No such file or directory)
> 2022-12-09 18:20:52:  INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/etc/netdata/conf.d/apps_groups.conf'
> 2022-12-09 18:20:52:  ERROR : MAIN : Cannot read process groups '/etc/netdata/conf.d/apps_groups.conf'. There are no internal defaults. Failing. (errno 2, No such file or directory)
> [root@192 ~]# /usr/libexec/netdata/plugins.d/apps.plugin 
> 2022-12-09 18:21:10: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/apps_groups.conf' (errno 2, No such file or directory)
> 2022-12-09 18:21:10: apps.plugin INFO  : MAIN : Cannot read process groups configuration file '/etc/netdata/apps_groups.conf'. Will try '/etc/netdata/conf.d/apps_groups.conf'
> 2022-12-09 18:21:10: apps.plugin ERROR : MAIN : PROCFILE: Cannot open file '/etc/netdata/conf.d/apps_groups.conf' (errno 2, No such file or directory)
> 2022-12-09 18:21:10: apps.plugin ERROR : MAIN : Cannot read process groups '/etc/netdata/conf.d/apps_groups.conf'. There are no internal defaults. Failing.
> ```
> 
> Stock files should be at `/usr` instead the cited directory.

I’m fairly certain this is a bug in the existing packages, and has nothing to do with the new repo hosting.

2022-12-12 13:06 UTC, thiagoftsm commented
Thank you @Ferroin , I will take a look when I return in these errors.

2022-12-12 13:07 UTC, thiagoftsm approved these changes
After @Ferroin explanation, and successful test on `CentOS 7.9`, we are ready to have a new repo. LGTM!

2022-12-12 15:58 UTC, Dim-P commented
@Ferroin While testing on `"Fedora Linux 37 (Server Edition)`:

```
[root@localhost netdata-Ferroin]# dnf update
Repository netdata-repoconfig is listed more than once in the configuration
Netdata                                                                581  B/s | 687  B     00:01
Netdata Repository Config                                               10  B/s |   9  B     00:00
Errors during downloading metadata for repository 'netdata-repoconfig':
  - Status code: 404 for https://repo.netdata.cloud/repos/repoconfig/fedora/37/x86_64/repodata/repomd.xml (IP: 172.67.72.170)
Error: Failed to download metadata for repo 'netdata-repoconfig': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Netdata Edge                                                           869  B/s | 687  B     00:00
Ignoring repositories: netdata-repoconfig
Dependencies resolved.
Nothing to do.
Complete!
```

`master` branch works find on `dnf update`.

2022-12-12 17:22 UTC, Ferroin commented
> Edit: Just noticed your comment "_Errors are expected for the Netdata Repository Config repository at the moment (we have no packages in that repo yet on the new infrastructure)._", so what I am seeing is normal I guess?

Correct, this particular error is expected right now.

2022-12-15 13:07 UTC, Dim-P approved these changes

2022-12-15 13:57 UTC, ilyam8 requested changes

2022-12-15 13:57 UTC, ilyam8 commented on packaging/repoconfig/netdata-edge.repo.centos
> +baseurl=https://repo.netdata.cloud/repos/repocnfig/el/$releasever/$basearch
```suggestion
baseurl=https://repo.netdata.cloud/repos/repoconfig/el/$releasever/$basearch
```

2022-12-15 14:08 UTC, ilyam8 approved these changes

2022-12-15 14:14 UTC, thiagoftsm approved these changes

2022-12-19 13:42 UTC, merged