Update get started doc
netdata/netdata pull request #14336
Opened 2023-01-26 18:16 UTC by Ancairon

##### Summary

This PR is related with https://github.com/netdata/documentation/issues/22, it includes:

- [X] Added a section called "Install Netdata", providing a very quick route to installing and claiming from the Cloud
- [X] The `wget` and `curl` options were put into tabs that Docusaurus provides
- [X] Fixed broken links with the proper (from now on) absolute github links
- [X] A note has been added to instruct the user to change the placeholders if he intends to claim to the Cloud
- [ ] Find a way to not have absolute raw links inside the install option boxes

What else could be changed:

- [ ] Do we need the top section "Get started with Netdata"? (Same information should be living at the introduction document)
- [X] ~~Should we rename the file's title to "Install Netdata"?~~ Already done due to naming conflict with the category this file lives at Learn
- [ ] Should we add another box in the "other installation options" for the "Install Netdata with kickstart.sh" page? (we have a link to it, but as a reference to the kickstart script)

2023-01-27 14:46 UTC, cakrit commented on docs/get-started.mdx
> +1. Visit https://app.netdata.cloud/
```suggestion
1. Sign up to https://app.netdata.cloud/
```

2023-01-27 14:50 UTC, cakrit commented on docs/get-started.mdx
> +Upon installation completing successfully, you should be able to see the node live in your Netdata Space!
```suggestion
Upon installation completing successfully, you should be able to see the node live in your Netdata Space!

Continue reading for more advanced instructions and installation options.
```

2023-01-27 14:52 UTC, cakrit commented on docs/get-started.mdx
> +For robust multi-node monitoring from a single interface, consider [Netdata Cloud](https://app.netdata.cloud/), which streams, aggregates, and visualizes metrics from any number of
Delete this. Our main instruction is WITH the cloud.

2023-01-27 14:56 UTC, cakrit commented on docs/get-started.mdx
> +[registry](https://github.com/netdata/netdata/blob/master/registry/README.md) is configurable to create a private "network" of Netdata dashboards.
The default registry isn't really worth mentioning here, very edge case.

2023-01-27 14:56 UTC, cakrit commented on docs/get-started.mdx
>  ### Need to monitor multiple nodes in one place?
Both securing and replication are strongly recommended. We'll probably create a dedicated page for production readiness, but not now.

2023-01-27 14:57 UTC, cakrit requested changes
See individual comments and handle them. Haven't looked at the widget yet.

2023-01-27 15:31 UTC, cakrit commented on docs/get-started.mdx
> +Both [securing](https://github.com/netdata/netdata/blob/master/docs/configure/secure-nodes.md) and [replication](https://github.com/netdata/netdata/blob/master/streaming/README.md) are strongly recom
```suggestion
Both [securing Netdata](https://github.com/netdata/netdata/blob/master/docs/configure/secure-nodes.md) and [setting up replication](https://github.com/netdata/netdata/blob/master/streaming/README.md) are strongly recommended.
```

2023-01-27 15:32 UTC, cakrit approved these changes

2023-01-30 15:54 UTC, thiagoftsm approved these changes

2023-01-30 17:03 UTC, merged