update the "Install Netdata with Docker" doc
netdata/netdata pull request #14385
Opened 2023-01-31 08:24 UTC by Ancairon

##### Summary

This PR is related with netdata/documentation#22, it includes:

- [X] Grouped the `docker run` and `docker-compose` options into a Tabs element
- [X] Added the note that the command for claiming can be found in Netdata Cloud -> Nodes -> Add Nodes (In the same manner that we did in the K8s PR) in each install option

I didn't fix the links, as there is a PR addressing the change already open.

2023-01-31 16:52 UTC, cakrit commented
The following are generic comments, but let's resolve the issues with this PR and then apply the solutions elsewhere too:
- You're talking about tabs, but I can't see tabs here. We can't have a PR that doesn't somehow show the end result.
- The markdown document is now full of directives that actually appear on the rendered github html page as garbage. Things like "note" or the scripting includes. There must be a better way to add these nice things, without compromising the quality of the page people see on github. @andrewm4894 got any ideas before I start digging?

2023-01-31 16:53 UTC, cakrit requested changes
See my comments in the main discussion, we'll need to somehow improve this process.

2023-01-31 17:29 UTC, Ancairon commented
> You're talking about tabs, but I can't see tabs here. We can't have a PR that doesn't somehow show the end result.

First thing that comes to my mind:

- I make a PR in netdata/netdata
- I make a branch in a local Learn clone
- I run the ingest on that local Learn branch, pulling from the netdata/netdata PR branch
- I push the branch to Learn
- If there is a regex system with setting auto-built branches in netlify (@tkatsoulas might have some insight in this), we can have a uniform way of naming those branches so we can have them auto-built.

That way you can look at the final product when reviewing and not reading through HTML elements and -I agree- "garbage" to the eye tags and Docusaurus jargon. 

I was doing this with some of the Learn staging branches that build automatically in the past, but this method will not scale efficiently.

If we make something automated, it would mean that we would be building every doc related PR 🤔 

>  There must be a better way to add these nice things, without compromising the quality of the page people see on github.

I can't think of a way that would not require having a duplicate place where we add the docusaurus elements, so that we can present the document to github users in this repo, it sounds like a version for GitHub and one for Docusaurus.
Ultimately if it is possible, the page would look different after the Docusaurus elements are added in.

2023-01-31 17:53 UTC, cakrit commented
I do like the idea of actually going through all the steps to see an actual preview, but the process you suggest seems to me to be a bit too involved @Ancairon . Could we automate it somehow?

@andrewm4894 @tkatsoulas do you have any other suggestions?

2023-02-07 18:12 UTC, cakrit requested changes
- The entire intro should be moved further down, we want to start with the docker-compose etc. 
- Completely remove the anonymous statistics warning, move it to the main installation page (get-started) to the bottom.
- Delete the first sentence completely.

2023-02-08 13:12 UTC, cakrit approved these changes

2023-02-08 13:12 UTC, merged