Update netdata-functions.md
netdata/netdata pull request #14441
Opened 2023-02-06 09:54 UTC by shyamvalsan

##### Summary

##### Test Plan

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

2023-02-06 14:07 UTC, hugovalente-pm requested changes
Just a request to add the GitHub discussion link that was open after the docs were merged

2023-02-06 14:07 UTC, hugovalente-pm commented on docs/cloud/netdata-functions.md
> +* Open a [feature request](https://github.com/netdata/netdata-cloud/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) on Netdata Cloud repo
```suggestion
* Participate in the relevant [GitHub discussion](https://github.com/netdata/netdata/discussions/14412)
* Open a [feature request](https://github.com/netdata/netdata-cloud/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) on Netdata Cloud repo
```

2023-02-06 14:07 UTC, hugovalente-pm commented on docs/cloud/netdata-functions.md
> +* Open a [feature request](https://github.com/netdata/netdata-cloud/issues/new?assignees=&labels=feature+request%2Cneeds+triage&template=FEAT_REQUEST.yml&title=%5BFeat%5D%3A+) on Netdata Cloud repo
I know it was not there before but since you are opening a PR on this taking the oportunity to add the Github discussion link 😁

2023-04-06 22:42 UTC, Dim-P commented
@shyamvalsan What's the status of this PR?

2023-07-31 08:57 UTC, hugovalente-pm approved these changes

2023-07-31 09:14 UTC, sashwathn approved these changes

2023-07-31 09:16 UTC, merged