Plans docs
netdata/netdata pull request #14491
Opened 2023-02-09 17:47 UTC by hugovalente-pm

##### Summary

Initial PR for the pages on:
* Netdata Plans
* View Plan & Billing

##### Test Plan

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

2023-02-09 17:49 UTC, hugovalente-pm commented
this is an initial PR, these docs can and should be improved with concrete examples of P90 calculations, different plan subscriptions and overage situations on yearly ones.
didn't want to have a blocker on those since these can be added alter

2023-02-09 18:52 UTC, cakrit commented on docs/cloud/manage/plans.md
> +> ⚠️
Make these two separate warnings, doesn't look good this way.

2023-02-09 18:57 UTC, cakrit requested changes
Very minor corrections here.

2023-02-09 18:57 UTC, cakrit commented on docs/cloud/manage/plans.md
> +> * On a move to Community, cancellation of an active subscription, please note that you will have all your notification methods configurations active for a period of 24 hours.
```suggestion
> * On a move to Community (cancellation of an active subscription), please note that you will have all your notification methods configurations active for a period of 24 hours.
```

2023-02-09 18:57 UTC, cakrit commented on docs/cloud/manage/plans.md
> +>   After that, any of those that won't available on your space's plan at that time will be automatically disabled. You can always re-enable them once you move to the proper paid plan.
```suggestion
>   After that, any notification methods unavailable in your new plan at that time will be automatically disabled. You can always re-enable them once you move to a paid plan that includes them.
```

2023-02-10 14:40 UTC, cakrit approved these changes

2023-02-10 14:44 UTC, cakrit requested changes
This PR suddenly includes a bunch of changes to the netdata code. Something happened between master and your branch Hugo, please rebase or start again with a new branch and PR.

2023-02-10 16:24 UTC, hugovalente-pm commented
> This PR suddenly includes a bunch of changes to the netdata code. Something happened between master and your branch Hugo, please rebase or start again with a new branch and PR.

@cakrit did a fix that Tasos told me about, this sometimes happens because some issue with GitHub. all should be good now

2023-02-10 17:02 UTC, cakrit approved these changes

2023-02-10 17:02 UTC, merged