Add metadata.csv to several modules
netdata/netdata pull request #14959
Opened 2023-04-25 11:20 UTC by Ancairon

##### Summary

As the title suggests, this PR adds metadata.csv to some modules.

2023-04-25 14:26 UTC, cakrit requested changes
I don't want a link to a csv in the documentation. Convert these to tables of metrics in markdown format please. 

Create a small script that just does that for now (takes as input the csv and spits out the markdown table). An additional manual step is then needed to edit the readme. 

The script may eventually be extended enough to generate the whole markdown document, but that's not a requirement for now.

2023-04-27 15:01 UTC, ilyam8 approved these changes

2023-04-27 15:13 UTC, thiagoftsm approved these changes

2023-04-27 16:08 UTC, cakrit approved these changes

2023-04-27 16:32 UTC, merged