systemd-journal plugin
netdata/netdata pull request #15363
Opened 2023-07-11 23:50 UTC by ktsaou

- [x] add a systemd-journal.plugin to netdata
- [ ] make it setuid to root so that it can retreive all the logs
- [ ] create a function that will expose the systemd log for any time frame requested
- [ ] make the function customizable to support facets and filters
- [ ] monitor systemd logs continiously and generate a few charts about them

2023-07-12 10:04 UTC, vkalintiris commented
@ktsaou why do we need this considering that we plan to merge the logs management PR?

2023-07-12 18:20 UTC, ktsaou commented
> @ktsaou why do we need this considering that we plan to merge the logs management PR?

Using netdata as a log management system is one decision.
Using netdata to view the logs that other log management systems have, is a different decision.

Especially for system logs, the ability to view them without actually doing anything is very important. This PR will allow all netdata dashboards to show the system logs of all systemd based systems, without actually any logs management system - just what the systems provide.

Eventually, we should be able to query any log management system. So, we should support also querying loki, elasticsearch, etc.

2023-08-03 12:01 UTC, Ferroin requested changes

2023-08-03 12:01 UTC, Ferroin commented on contrib/debian/rules
> +
Correction to my earlier statement, can we drop this for the moment? It’s failing right now due to the plugin not actually getting built (due to missing deps which will need to be handled in a separate PR).

2023-08-03 12:41 UTC, Ferroin approved these changes

2023-08-03 12:42 UTC, merged