Remove __builtin_expect from our codebase.
netdata/netdata pull request #15480
Opened 2023-07-21 09:13 UTC by vkalintiris

##### Summary

Here's what GCC's manual has to say:

> In general, you should prefer to use actual
> profile feedback for this (-fprofile-arcs),
> as programmers are notoriously bad at
> predicting how their programs actually
> perform.

Indeed, using the profile plugin with:

- 16 threads
- 400 charts per thread
- 5 dimensions per chart,
- 1M points to backfill per dim,

leads to a consistent, small improvement of
2-3% in the rate of total points written
per second when **removing** the builtin.

There are definitely some places where we
could benefit from using `__builtin_expect`.
However:
  - Currently, we use it everywhere which negates any improvements.
  - We need to profile each location where we use the builtin.

In general, the agent is memory bound for most
of its heavy operations. I don't think:
  - we can easily outsmart compilers + post-2000s CPUs, and
  - there's any real-world scenario where using this builtin would show up any visible difference.

Removing the builtin makes the code much more
readable.

##### Test Plan

- CI jobs

2023-07-21 09:13 UTC, vkalintiris commented
Automatically generated with https://gist.github.com/vkalintiris/270a469b0465fbe429be03f613791a7d

2023-07-21 10:06 UTC, ilyam8 requested changes
We did the following tests with @ktsaou some time ago:

 1. master
 2. reversed likely/unlikely
 3. without likely/unlikely

2 was much slower, and 3 was significantly slower too.

I don't remember the exact numbers and tests we did but it was like 2-3 times slower (or more).

2023-07-21 10:57 UTC, vkalintiris commented
> We did the following tests with @ktsaou some time ago (I also assumed that we could remove all these likely/unlikely):
> 
> 1. master
> 2. reversed likely/unlikely
> 3. without likely/unlikely
> 
> 2 was much slower, and 3 was significantly slower too.
> 
> I don't remember the exact numbers and tests we did but it was like 2-3 times slower (or more).

Prove me wrong but there's no way for that builtin to impact performance anywhere near that much in a real application.

> 
> I think we need more tests/discussions before considering merging this (removing them completely from the codebase and not only where they are not needed). cc @ktsaou

Open to any suggestions on what kind of tests we can ran. AFAIC, the only reasonable test we can still do is running this on the lab parents and check any difference. I doubt there will be any.

2023-08-02 20:10 UTC, ktsaou commented
Please don't merge this yet. Let's do some tests first.

I am sure some of our manual interventions are wrong, but there are many parts they are crucial. In many case we know that the happy path should be fixed and the exceptions should be slower, and if we remove all these, I am not sure what will happen.


So, please let's review this in detail.

2023-12-14 18:52 UTC, closed without merging