add rrddim_get_last_stored_value to simplify function code in internal collectors
netdata/netdata pull request #16348
Opened 2023-11-06 16:46 UTC by ilyam8

##### Summary

ssia

##### Test Plan

Check internal collectors functions.

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

2023-11-06 17:44 UTC, thiagoftsm submitted a review, later dismissed
PR is working as expected, LGTM!

2023-11-06 19:48 UTC, stelfrag commented on collectors/diskspace.plugin/plugin_diskspace.c
> +        double inodes_avail = rrddim_get_last_stored_value(mp->rd_space_avail, &max_space_avail, 1.0);
Please check the inodes calculations

2023-11-07 08:14 UTC, vkalintiris requested changes
@ilyam8 I'm pedantic with this one because it touches the API of `database/`.

2023-11-07 08:49 UTC, ilyam8 commented on database/rrd.h
> +static inline double rrddim_get_last_stored_value(RRDDIM *rd_dim, double *max_value, double div) {
> or even better create a new file collectors/common.h

I agree with that. I tried to make it static and put in `collectors/all.h` but it dodn't work. I asked on Slack and was told to put in rrd.h which I did. @stelfrag @MrZammler if you can address @vkalintiris request please help and push a commit to this PR.

2023-11-07 11:17 UTC, vkalintiris approved these changes
LGTM considering that doing the changes I  asked is not trivial due to the way we currently organize headers. I'll try to cleanup the headers myself in the future.

2023-11-07 11:49 UTC, stelfrag approved these changes

2023-11-07 11:53 UTC, merged