Move config.cmake.h.in under src/libnetdata.
netdata/netdata pull request #16906
Opened 2024-02-01 14:34 UTC by vkalintiris

##### Summary

SSIA.

##### Test Plan

- CI jobs.

2024-02-01 17:59 UTC, stelfrag approved these changes

2024-02-04 19:39 UTC, thiagoftsm requested changes
Please, take a look in RPM issues.

2024-02-05 09:18 UTC, vkalintiris commented
> Please, take a look in RPM issues.

Yes, I've marked the PR as draft again because of these failures. I want to finish migrating the rest of the top-level directories that contain source code of the agent under `src/` before taking a look at this PR again.

2024-02-26 13:28 UTC, thiagoftsm approved these changes
As OpenSuse issue is expected right now, everything is working with this PR, so LGTM!

2024-02-26 13:48 UTC, merged