Rename a variable in FreeIMPI (WolfSSL support)
netdata/netdata pull request #17687
Opened 2024-05-16 18:39 UTC by thiagoftsm

##### Summary
This PR address an issue reported on Slack:

```sh
[105/370] Building C object CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o
FAILED: CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o 
/usr/bin/cc -D_GNU_SOURCE -I/usr/include/uuid -I/home/stelios/git/netdata/cmake-build-debug -I/home/stelios/git/netdata/src -I/usr/include/json-c -I/home/stelios/git/netdata/src/libnetdata/libjudy/src -I/home/stelios/git/netdata/src/libnetdata/libjudy/src/JudyCommon -Wall -Wextra -Wmaybe-uninitialized -g -std=gnu11 -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wno-builtin-macro-redefined -fexceptions -MD -MT CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o -MF CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o.d -o CMakeFiles/freeipmi.plugin.dir/src/collectors/freeipmi.plugin/freeipmi_plugin.c.o -c /home/stelios/git/netdata/src/collectors/freeipmi.plugin/freeipmi_plugin.c
/home/stelios/git/netdata/src/collectors/freeipmi.plugin/freeipmi_plugin.c:108:5: error: 'protocol_version' redeclared as different kind of symbol
  108 | int protocol_version = -1;      // IPMI_MONITORING_PROTOCOL_VERSION_1_5, etc. or -1 for default
      |     ^~~~~~~~~~~~~~~~
In file included from /home/stelios/git/netdata/src/libnetdata/ssl/ssl.h:32,
                 from /home/stelios/git/netdata/src/libnetdata/libnetdata.h:486,
                 from /home/stelios/git/netdata/src/collectors/freeipmi.plugin/freeipmi_plugin.c:22:
/usr/include/wolfssl/ssl.h:761:5: note: previous definition of 'protocol_version' with type 'enum AlertDescription'
  761 |     protocol_version                =  70,
````

##### Test Plan

##### Additional Information

<details> <summary>For users: How does this change affect me?</summary>
  
</details>

2024-05-16 19:30 UTC, stelfrag submitted a review, later dismissed

2024-05-20 08:04 UTC, ilyam8 requested changes
You missed

https://github.com/netdata/netdata/blob/05dd823fed621240511fed2a87a9fb0ead722e02/src/collectors/freeipmi.plugin/freeipmi_plugin.c#L1882

2024-05-20 14:45 UTC, stelfrag approved these changes

2024-05-20 16:39 UTC, ilyam8 approved these changes

2024-05-20 16:40 UTC, merged