[WIP] Run the agent as a Windows service.
netdata/netdata pull request #17766
Opened 2024-05-28 13:49 UTC by vkalintiris

##### Summary

This commit contains the boilerplate code for running the agent as a Windows service.

We start the agent's main as a separate thread, although this is not strictly required based on my experiments. We need similar logic for calling netdata's exit function when someone wants to stop the agent.

However, at this point we need to resolve the issue of gaps when running the agent as a service. It seems that sleeping for one second with `sleep(1)`, actually sleeps for 2 to 4 seconds on my setup.

Once we resolve this, the work that remains concerns packaging: ie. installing the binaries at the proper places so that the relevant DLLs are found.

To test this PR you need to:
  - Build the agent: ./packaging/utils/compile-on-windows.sh
  - Install the files: `ninja -C build/ install`
  - Copy the main binary: `cp ./build/netdata /usr/bin/`
  - (Only once) Create the netdata service: `sc.exe config Netdata binPath="C:\msys64\usr\bin\netdata"`
  - Start the service: `sc.exe start Netdata`

A couple notes:
  - The health and the spawn client have been disabled for the time being. They will be re-enabled once we finish the agent-as-service issue and the packaging.
  - Last time I checked, the agent crashes after a while when using dbengine. In order to have something that works correctly, you should specify memory-mode ram in your netdata.conf.

##### Test Plan

- N/A.

2024-05-28 22:49 UTC, thiagoftsm commented
> However, at this point we need to resolve the issue of gaps when running the agent as a service. It seems that sleeping for one second with sleep(1), actually sleeps for 2 to 4 seconds on my setup.

This is expected. Now that we are working with Microsoft, we need to use more deep their own API, for example:

- We have [Sleep](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep) function that probably calls [SleepEx](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleepex).
- We can also use [CreateWaitable](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerw?redirectedfrom=MSDN)

When we call some normal function that we use on Linux, in normal situation it is converted to some internal windows function. 

We also need to have in our minds that Microsoft does not measure time like Unix. They update internal counters each [100 ns](https://learn.microsoft.com/en-us/windows/win32/sysinfo/file-times).

2024-05-28 22:50 UTC, thiagoftsm commented
> Once we resolve this, the work that remains concerns packaging: ie. installing the binaries at the proper places so that the relevant DLLs are found.

Please, do not forget to require administrative privileges to install the Service. I remember some installers have option to do this.

2024-05-28 22:53 UTC, thiagoftsm commented
> (Only once) Create the netdata service: sc.exe config Netdata binPath="C:\msys64\usr\bin\netdata"

I still did not study the source code, but I suggest changing this. Let us add two new options:

- --install-service: This option will be used by installer for netdata register itself as a Service.
- --remove-service: Remove netdata service.

If it is planned to remove and install the service with an installer, this suggestion can be ignored.

2024-05-28 22:55 UTC, thiagoftsm commented
> Last time I checked, the agent crashes after a while when using dbengine. In order to have something that works correctly, you should specify memory-mode ram in your netdata.conf.

This probably has relationship with threads or permissions. I will run netdata with debugger to check.

2024-05-28 23:05 UTC, thiagoftsm commented on src/daemon/main.c
> +int netdata_main(int argc, char **argv)
A comment: I understand we are still not using a [WinMain](https://learn.microsoft.com/en-us/windows/win32/learnwin32/winmain--the-application-entry-point) as an entry point, but we will have it one day.

2024-05-28 23:07 UTC, thiagoftsm commented on src/daemon/winsvc.cc
> +    std::ofstream log("/opt/netdata/var/log/netdata/service.log", std::ios_base::app);
Probably we should start using `C:\\Program Files\\Netdata`. :thinking:

2024-05-29 13:32 UTC, thiagoftsm commented
I thought this could be the scenario, so I decided to test:

![Screenshot_20240529_133008](https://github.com/netdata/netdata/assets/49162938/8a4991ee-5b03-4e16-b1e2-cc2bffe0c960)

When we run direct on Windows, ignoring `msys`, we have an error.

2024-05-30 00:59 UTC, thiagoftsm commented
@vkalintiris , please, change :

```sh
sc.exe config Netdata binPath="C:\msys64\usr\bin\netdata"
```

to

```sh
sc.exe create "Netdata" binpath="C:\msys64\usr\bin\netdata"
```

2024-05-30 01:33 UTC, thiagoftsm commented
When I run this `sc.exe create "Netdata" binpath="C:\msys64\usr\bin\netdata"`, the service does not initiate. I receive error `1053`. According to `Event Viewer`, the service did not start in 30 seconds, independent of memory mode.

2024-05-30 09:17 UTC, vkalintiris commented
> > However, at this point we need to resolve the issue of gaps when running the agent as a service. It seems that sleeping for one second with sleep(1), actually sleeps for 2 to 4 seconds on my setup.
> 
> This is expected. Now that we are working with Microsoft, we need to use more deep their own API, for example:
> 
> * We have [Sleep](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep) function that probably calls [SleepEx](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleepex).
> * We can also use [CreateWaitable](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerw?redirectedfrom=MSDN)
> 
> When we call some normal function that we use on Linux, in normal situation it is converted to some internal windows function.
> 
> We also need to have in our minds that Microsoft does not measure time like Unix. They update internal counters each [100 ns](https://learn.microsoft.com/en-us/windows/win32/sysinfo/file-times).

I'll check the timings of these functions, but I don't see how `sleep()` could digress so much because it should use one of those behind the scenes.

2024-05-30 09:18 UTC, vkalintiris commented
> > (Only once) Create the netdata service: sc.exe config Netdata binPath="C:\msys64\usr\bin\netdata"
> 
> I still did not study the source code, but I suggest changing this. Let us add two new options:
> 
> * --install-service: This option will be used by installer for netdata register itself as a Service.
> * --remove-service: Remove netdata service.
> 
> If it is planned to remove and install the service with an installer, this suggestion can be ignored.

The installer will be an executable that someone can download and start. The installer will be responsible for installing the uninstaller as well in order to allow people to uninstall the agent if they wish.

2024-05-30 09:19 UTC, vkalintiris commented on src/daemon/winsvc.cc
> +        WriteLog("@main() - StartServiceCtrlDispatcher() failed...");
We want to create the service with `sc.exe` at installation time, instead of adding this logic in the agent itself.

2024-05-30 09:20 UTC, vkalintiris commented
> I thought this could be the scenario, so I decided to test:
> 
> ![Screenshot_20240529_133008](https://private-user-images.githubusercontent.com/49162938/334818702-8a4991ee-5b03-4e16-b1e2-cc2bffe0c960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjA4NzUsIm5iZiI6MTcxNzA2MDU3NSwicGF0aCI6Ii80OTE2MjkzOC8zMzQ4MTg3MDItOGE0OTkxZWUtNWIwMy00ZTE2LWIxZTItY2MyYmZmZTBjOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA5MTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2Njg0NDVjNGQ4ZDAyOTc0Y2M1NTU4NGM3NTgzZGQ4ODIzM2Y4MTIzOTc3ZjI4OWZlOTc1NGJjNWE4MGMxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1nfDGZhsZVgWWkCtNunnKo2Zu7ntYj7IsvmaMdWYlE)
> 
> When we run direct on Windows, ignoring `msys`, we have an error.

A feature not a bug, at this point.

2024-05-30 09:21 UTC, vkalintiris commented
> When I run this `sc.exe create "Netdata" binpath="C:\msys64\usr\bin\netdata"`, the service does not initiate. I receive error `1053`. According to `Event Viewer`, the service did not start in 30 seconds, independent of memory mode.

`sc.exe create ...` creates the service, it should not start it. Did you mean to say something else?

2024-05-30 11:48 UTC, vkalintiris commented
> > > However, at this point we need to resolve the issue of gaps when running the agent as a service. It seems that sleeping for one second with sleep(1), actually sleeps for 2 to 4 seconds on my setup.
> > 
> > 
> > This is expected. Now that we are working with Microsoft, we need to use more deep their own API, for example:
> > 
> > * We have [Sleep](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep) function that probably calls [SleepEx](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleepex).
> > * We can also use [CreateWaitable](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createwaitabletimerw?redirectedfrom=MSDN)
> > 
> > When we call some normal function that we use on Linux, in normal situation it is converted to some internal windows function.
> > We also need to have in our minds that Microsoft does not measure time like Unix. They update internal counters each [100 ns](https://learn.microsoft.com/en-us/windows/win32/sysinfo/file-times).
> 
> I'll check the timings of these functions, but I don't see how `sleep()` could digress so much because it should use one of those behind the scenes.

Apparently, on Windows the highest resolution sleep is 1 msec. We use various kind of sleep functions throughout the entire codebase. For time being, I've only updated the sleep function that is called within the `heartbeat_next` function. I don't notice any gaps in the charts now. However, other places in the agent might need to be updated as well, in the future.

2024-06-02 09:56 UTC, StefanSa commented
@vkalintiris, @ktsaou  Hi there,
I had the service startup problem with exactly the same error message, currently i solved this with a service wrapper.
I have created an installer for netdata with InnoSetup.
It installs netdata and the necessary dll's regardless of the file path, so you don't have to install msys2.
The netdata service is also installed. The uninstall routine also works without any problems.
Currently i am still optimizing for updates with InnoSetup and netdata.
If you like, i can provide you with the installation script of InnoSetup.

2024-06-03 02:42 UTC, thiagoftsm requested changes
Considering I am not unique to have [issues](https://github.com/netdata/netdata/pull/17766#issuecomment-2143780288) and considering that we also have issues to do cross-compilation due `pthread`, I am doing this `request change` to avoid merge this PR until we address all issues.

2024-06-03 18:42 UTC, thiagoftsm commented
> When I run this `sc.exe create "Netdata" binpath="C:\msys64\usr\bin\netdata"`, the service does not initiate. I receive error `1053`. According to `Event Viewer`, the service did not start in 30 seconds, independent of memory mode.

Hello @vkalintiris ,

I still have the same issue. I am doing the following steps to have it:

##  On Windows prompt
- I start a terminal as administrator and I ran: `sc delete "Netdata"`

## On Msys2
- I clone your branch
- I compiled it

## On Windows prompt
-  I ran: sc.exe create "Netdata" binpath="C:\msys64\opt\netdata\usr\sbin\netdata.exe"

## On Windows
- I went to Start -> `run` and I wrote `services.msc`
- I found the `Netdata` service installed, and I tried to start it.

Best regards.

Thiago

2024-06-08 00:00 UTC, thiagoftsm commented on src/libnetdata/locks/locks.h
> +    netdata_mutex_t inner;
When we cross compile our code on Linux, `netdata_mutex_t` is one of the issues raised. Is there the possibility we already start using Windows native functions and data type? Or to use `libuv`?

2024-06-10 12:31 UTC, vkalintiris commented
@thiagoftsm @stelfrag Please, check the PR's description if you want to give it a try. Post any errors you might find here.

2024-06-13 14:01 UTC, vkalintiris commented
@thiagoftsm @stelfrag The latest commit disables pluginsd. Without it the agent starts up correctly all the time. AFAIC, this unblocks the Windows release, considering that we don't rely on pluginsd for collecting Windows metrics. Of course, I'll keep investigating until I find the real, underlying cause of the problem.

2024-06-13 17:06 UTC, StefanSa commented
@vkalintiris,  Thanks for your time and effort.
but i can't get the agent from your WIndows branch to work
`git clone -b windows https://github.com/vkalintiris/netdata.git`
`git submodule init && git submodule update`
`packaging/utils/compile-on-windows.sh`

Copy the necessary dlls to it, but when starting in the cmd box nothing is displayed at all,
no error message can be seen in the event list either.
It starts for a brief second and then stops.
This works in the original repo without any problem, except that the agent does not run as a service and you have to use a service wrapper. Any idea where the problem could be?

2024-06-13 20:27 UTC, vkalintiris commented
> @vkalintiris,  Thanks for your time and effort.
> but i can't get the agent from your WIndows branch to work
> `git clone -b windows https://github.com/vkalintiris/netdata.git`
> `git submodule init && git submodule update`
> `packaging/utils/compile-on-windows.sh`
> 
> Copy the necessary dlls to it, but when starting in the cmd box nothing is displayed at all,
> no error message can be seen in the event list either.
> It starts for a brief second and then stops.
> This works in the original repo without any problem, except that the agent does not run as a service and you have to use a service wrapper. Any idea where the problem could be?

I have updated the PR description. You need to create the installer and setup the service for this to work.

2024-06-13 23:09 UTC, thiagoftsm commented
Hello @StefanSa ,

When you talk about `cmd`, I understand this is the windows terminal instead `msys` terminal, please, can you confirm this?

I have tested this PR on `msys` and also on windows terminal, and I observed fails when I am running on the last.

I will test now latest commits.

Best Regards,

Thiago!

2024-06-14 00:25 UTC, thiagoftsm commented on src/daemon/winsvc.cc
> +static void *call_netdata_main(void *arg)
This static function is not used.

2024-06-14 01:13 UTC, thiagoftsm commented
@vkalintiris ,

After last commits, when I try to start the daemon running the command on terminal, I observe that `netdata` was installed in `/opt/netdata`, but the daemon is trying to write logs in `/var/log/netdata`. Of course, this is not expected, so it `daemon` ends with error 1.

2024-06-14 02:11 UTC, thiagoftsm commented
@vkalintiris ,

Please, add a description to netdata service:

![missingdesc](https://github.com/netdata/netdata/assets/49162938/b71c52db-36da-479d-91d3-6403b88a8118)

I could install using our installer, but it fails when I used manual commands as I described previously. If the goal is always to use the installer, we will have to add messages  (I am not saying logs, I am talking about [MessageBoxes](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxexa)) to give proper information for our users;

2024-06-14 02:13 UTC, thiagoftsm commented
When I try to stop the service, I have error `1067`:  "Netdata service end was unexpected"

2024-06-14 02:16 UTC, thiagoftsm commented
Our installer is not checking a previous netdata installed, this should not happen. If we have a netdata service installed, it should report there is a previous version, or it would need to say that we are going to update. We are repeating the same steps and we try to reinstall the service..

2024-06-14 02:20 UTC, thiagoftsm commented
We have the `Unistaller` inside `C:\Program Files\netdata`, but we do not have any information inside `Control Panel - > Software`. Users should also be able to remove netdata from there.

2024-06-14 02:52 UTC, StefanSa commented
@thiagoftsm 

Yes, i have only tested this in the cmd terminal,
because i do not want to install msys2 with the
it is sufficient to copy only the necessary msys2 dll. I also see the error 1067 when i try to install the service with my installer.
As already described, i have no problems with the original metadata branch, except that i currently have to use a service wrapper because the native agent does not start as a Service.

2024-06-14 17:13 UTC, thiagoftsm commented
@StefanSa, thank you to confirm, and test this PR.

@vkalintiris now we have a confirmation that is not something related to a specific environment.

2024-06-19 23:57 UTC, thiagoftsm commented
When we try to use `sc.exe` on windows command line we still have issues to start service. The error is `1053`, but there is a difference this time, my Service controller this time was frozen.

When I ran the new installer created with OP instructions:, I had the following scenario:

- It did not give me option to select destination and it removed completely my development environment on Microsoft.
- It did not create the service.

Finally, I do not know why we changed the installer screen, but I think the previous were more user-friendly.

2024-06-20 12:52 UTC, vkalintiris commented
@thiagoftsm give the PR another round of tests (test only the installer and/or sc.exe start/stop/delete, ie. not RUN_FROMM_CLI). AFAICT, it should be working now. However, there are still some issue we'll have to address.

2024-06-20 17:57 UTC, thiagoftsm commented
@vkalintiris ,

After last commits, I am not able to make the installer. I am having this error:

![Commits](https://github.com/netdata/netdata/assets/49162938/e77e8ebb-5a6c-4756-b29f-0dee6b233991)

2024-06-21 06:53 UTC, vkalintiris commented
> @vkalintiris ,
> 
> After last commits, I am not able to make the installer. I am having this error:
> 
> ![Commits](https://private-user-images.githubusercontent.com/49162938/341515499-e77e8ebb-5a6c-4756-b29f-0dee6b233991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTI5ODksIm5iZiI6MTcxODk1MjY4OSwicGF0aCI6Ii80OTE2MjkzOC8zNDE1MTU0OTktZTc3ZThlYmItNWE2Yy00NzU2LWIyOWYtMGRlZTZiMjMzOTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2NTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMWI1ZDFjNmE2NTU1Y2FhYWM3YzNhMWNiMjQ4ZTNiNjFmNTkyMDNlOTdiOWJkNGVmOTZkOWVlYmNjZTZkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.22MRTuPUDNKDwOG_EB4F_ykah7L7SCuG8zUoKq81myE)

You installed msys2 under `C:\msys64_dev`, the packaging script expects the default installation path, ie. `C:\msys64`.

2024-06-23 15:54 UTC, StefanSa commented
@vkalintiris 
i can confirm that your last commit works with the installer and service.
But what i notice is the following. A start in the msys2 or cmd terminal fails without any hint / message in the terminal directly after the start. It seems that this version can only be started as a service. How can i tell the service / agent the path of the netdtata.conf (-c), or where does the current agent get its information from which netdata.conf (usr\lib\netdata\conf.d) ?
One more important thing, the installer does not make an entry in "Programs and Features", so that it cannot be uninstalled via this. Likewise, not everything is uninstalled, empty folders remain, e.g. (netdata\usr\sbin).

2024-06-25 12:25 UTC, thiagoftsm commented
> You installed msys2 under `C:\msys64_dev`, the packaging script expects the default installation path, ie. `C:\msys64`.

I think we need to change our script to get current local directory. I had to create the environment without default targets, because last time I used the installer, it overwrites everything.

2024-06-28 20:21 UTC, ktsaou commented
Guys, I need this to continue working on windows.
Please review and merge asap.

2024-06-29 12:10 UTC, StefanSa commented
Hi there,
can now confirm that the netdata agent also works in the terminal.

i still have a few thoughts about the installer:
- The installer should be able to perform updates when the version number increases.
  To do this, the service must be stopped beforehand, otherwise the update will fail.

- Package name should contain version name and platform, e.g. netdata-1.46.0.446-x64.exe
  
  ![image](https://github.com/netdata/netdata/assets/6105075/69dd7ecd-d8a4-4b59-8155-dc574d77c0fd)

- It would be important to specify the path of the config file in the service using "-c".
  However, this would require a placeholder / variable in the config file, which the installer fills in with the correct path.

- The installer should make an entry in "Programs and Features", so that an uninstallation can be executed here.

  ![image](https://github.com/netdata/netdata/assets/6105075/69dd7ecd-d8a4-4b59-8155-dc574d77c0fd)

- When removing the app, no files or folders should be left behind, everything must be uninstalled.

- Asking the user whether the service should be started after installation or stopped during the update increases the user 
  experience.

- It would be nice if the installer showed the Netdata logo.

  ![image](https://github.com/netdata/netdata/assets/6105075/73ea90ee-cdf3-4116-b9e8-092e98bbfcd9)

2024-07-01 01:24 UTC, thiagoftsm commented
@vkalintiris ,

Everything said by @StefanSa is right, I do not have nothing to add.

> When removing the app, no files or folders should be left behind, everything must be uninstalled.
On my environment I observed we still have `/usr` and `/var` kept. 

Considering everything critical was fixed. I am going to approve it for we unblock @ktsaou and also myself, but we cannot forgot what @StefanSa mentioned. 

Best regards!

2024-07-01 01:25 UTC, thiagoftsm approved these changes
I am approving because there is not more critical issues, but, again, the minor issues must be address with another PR.

2024-07-02 09:19 UTC, merged

2024-07-02 09:28 UTC, vkalintiris commented
@StefanSa I'll address most of your suggestions in follow up PRs. We had to merge this to unblock the rest of the team.