Fix openldap  tls over ldap
netdata/netdata pull request #9853
Opened 2020-08-31 14:45 UTC by scatenag

##### Summary

Since [`ldaps:// `is deprecated](https://www.openldap.org/faq/data/cache/605.html), we use TSL over `ldap://` with `start_tsl` on our LDAP server; that case is not covered by the code.

I added the option `use_start_tls` by `sudo ./edit-config python.d/openldap.conf` and managed them in  `/usr/libexec/netdata/python.d/openldap.chart.py` .

##### Component Name

python.d/openldap

##### Test Plan

I tested it for TSL over `ldap://` with `start_tls`;
we should test if TSL over `ldaps://` is not broken.

##### Additional Information

Related to [issue 9004](https://github.com/netdata/netdata/issues/9004).

2020-08-31 14:58 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-08-31 16:44 UTC, ilyam8 commented
@scatenag hi, thx for the contribution!

There are tabs in the PR, convert them to spaces.

2020-08-31 17:19 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-08-31 17:31 UTC, ilyam8 requested changes

2020-08-31 17:31 UTC, ilyam8 commented on collectors/python.d.plugin/openldap/openldap.chart.py
> +                self.conn.set_option(ldap.OPT_X_TLS_NEWCTX,0)
```diff
-                self.conn.protocol_version=ldap.VERSION3
-                self.conn.set_option(ldap.OPT_X_TLS_NEWCTX,0)
+                self.conn.protocol_version = ldap.VERSION3
+                self.conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
```

2020-08-31 17:36 UTC, ilyam8 commented
@scatenag 

It is not related to thi PR, but lets change this part too

I noticed that it is possible to reference `val` var before assignment

https://github.com/netdata/netdata/blob/c857c880f31a89b7857bf01f1f48227c41bf8a93/collectors/python.d.plugin/openldap/openldap.chart.py#L200-L207

to

```python
  if result_type != 101:
    continue

  try: 
    data[key] = int(list(result_data[0][1].values())[0][0]) 
  except (ValueError, IndexError) as error: 
    self.debug(error) 
    continue 
```

2020-09-01 07:13 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-09-01 07:19 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-09-01 07:39 UTC, ilyam8 commented
> we should test if TSL over ldaps:// is not broken.

do we need someone or you can do it? @scatenag

2020-09-01 08:24 UTC, scatenag commented
> > we should test if TSL over ldaps:// is not broken.
> 
> do we need someone or you can do it? @scatenag

Actually, to make it works (with ldaps:// on port 636) on my env, I had to modify the code adding
`self.conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)` also on the `use_tls` side
(otherwise I got `{'info': u'(unknown error code)', 'errno': 2, 'desc': u"Can't contact LDAP server"}`).

Maybe another tester is needed?

2020-09-01 08:27 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-09-01 08:33 UTC, ilyam8 commented
Shouldnt we change `unbind` to `unbind_s`?

https://github.com/netdata/netdata/blob/d521566bc264788413a8d176d4c75045c873f0a8/collectors/python.d.plugin/openldap/openldap.chart.py#L149-L151

i found my comment (dont remember details)

https://github.com/netdata/netdata/issues/5783#issuecomment-479360977

2020-09-01 08:34 UTC, ilyam8 commented
Did you test reconnect? (disable openldap server; wait; enable openldap server)

2020-09-01 08:42 UTC, scatenag commented
> Shouldnt we change `unbind` to `unbind_s`?
> 
> https://github.com/netdata/netdata/blob/d521566bc264788413a8d176d4c75045c873f0a8/collectors/python.d.plugin/openldap/openldap.chart.py#L149-L151
> 
> i found my comment (dont remember details)
> 
> [#5783 (comment)](https://github.com/netdata/netdata/issues/5783#issuecomment-479360977)

Probably `unbind_s` doesn't broke anything;
I tested in my env for `ldap://:` with `start_tls` and for `ldaps://`.

[The documentation ](https://www.python-ldap.org/en/python-ldap-3.3.0/reference/ldap.html?highlight=unbind#ldap.LDAPObject.unbind)is not very useful in this case...

2020-09-01 08:45 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-09-01 08:46 UTC, ilyam8 commented
if i understand you right you cant test with `ldap://` and without `start_tls`, am i right?

2020-09-01 08:51 UTC, scatenag commented
> if i understand you right you cant test with `ldap://` and without `start_tls`, am i right?

Yes; I can test only
- `ldap://` with `start_tls`
- `ldaps://`

Anyway, the only modification to `ldap://` without tls is
`self.conn.simple_bind_s` for `self.conn.simple_bind`.

If you want, we can use `self.conn.simple_bind_s` only for `use_tls` and `use_start_tls`...
should I make this revision?

2020-09-01 09:28 UTC, ilyam8 commented
> If you want, we can use self.conn.simple_bind_s only for use_tls and use_start_tls...
should I make this revision?

this looks ok since we cant test `ldap://` without `start_tls`

2020-09-01 09:44 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-09-01 10:37 UTC, ilyam8 commented
Ok, difference between `func` and `func_s` is synchronous/asynchronous calls. I think we can use `func` funcs. Does it work for you? Why did you change bind to bind_s?

2020-09-01 11:06 UTC, scatenag commented
You are right!
Reverted.

2020-09-01 11:07 UTC, ktsaou commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- collectors/python.d.plugin/openldap/openldap.chart.py  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/netdata/netdata/pullRequest?prid=6098045&bid=19963423)

2020-09-01 11:40 UTC, ilyam8 approved these changes

2020-09-01 11:41 UTC, ilyam8 commented
@scatenag lgtm 👍

2020-09-01 11:42 UTC, ilyam8 commented
@scatenag does this PR fix #9004

2020-09-01 12:05 UTC, vlvkobal approved these changes

2020-09-01 12:57 UTC, merged