Add configure docs to docsv2 project
netdata/netdata pull request #9878
Opened 2020-09-03 21:46 UTC by joelhans

##### Summary

Moving into configuration. Two documents for Cloud-specific configurations, and then another two documents for node configuration basis and improving security of nodes.

> See netdata/netdata-learn-docusaurus#285 for additional context.
>
> This page contains some elements that will only appear on the deployed Learn site, so see the deploy preview for this page for the full picture: https://deploy-preview-285--netdata-docusaurus.netlify.app/docs/get
>
> Some links will not work, as the target docs do not exist yet.
>
> For now, these PRs will get merged into the docsv2 but not go live on Netdata Learn. Once they're all available, or at least a workable majority, we'll merge them into master and deploy the project as a whole.

##### Component Name

area/docs

##### Test Plan

##### Additional Information

2020-09-04 20:58 UTC, aabatangle requested changes

2020-09-04 20:58 UTC, aabatangle commented on docs/configure/spaces-war-rooms.md
> +Spaces with an appreviated version of each's name, and you can click on any of the icons to switch between them.
appreviated --> abbreviated? also, "each's" is a little confusing to me.

2020-09-04 20:58 UTC, aabatangle commented on docs/configure/spaces-war-rooms.md
> +For example, a large organization might have one SRE team for the user-face SaaS application, and a second IT team for
user-facing?

2020-09-04 20:58 UTC, aabatangle commented on docs/configure/spaces-war-rooms.md
> +managing employee's hardware. Since these teams don't monitor the same nodes, they can work in separate Spaces and then
employees'

2020-09-08 15:03 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +Choose which War Rooms you want to add this user to, then click the plus **+** button to add the invitation to the
Admins manage user permissions and have control over who can access specific Spaces and War Rooms.

2020-09-08 15:05 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +
Admins manage user permissions and have control over who can access specific Spaces and War Rooms.

2020-09-08 15:06 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +
```suggestion
Admins manage user permissions and have control over who can access specific Spaces and War Rooms.

```

2020-09-08 15:07 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +Your team will receive their invitations momentarily and prompt them to sign in to join your Space.
```suggestion
Your team will receive their email invitations momentarily and prompt them to sign in to join your Space.
```

2020-09-08 15:10 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +Nginx log metrics, another can dive into the real-time node dashboard investigate correlated charts in granular detail.
```suggestion
Nginx log metrics, another can dive into the real-time node dashboard and investigate correlated charts in granular detail.
```

2020-09-08 15:12 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +for example, to increase metrics retention and improve security.
```suggestion
for example, to increase metrics retention with [Netdata's Database](hhttps://learn.netdata.cloud/docs/agent/database/engine) engine or improve security.
```

2020-09-08 15:18 UTC, jlbriston commented on docs/configure/invite-collaborate.md
> +for example, to increase metrics retention and improve security.
Perhaps the "Improve security" can link to the "secure your nodes" documentation

2020-09-08 15:40 UTC, jlbriston approved these changes

2020-09-09 18:42 UTC, merged